/*
 * mbhrouts2d.c
 *
 * C translation of src/modified-biharmonic/mbhrouts2d.f
 * Multipole/local expansion routines for modified biharmonic FMM.
 *
 * Generated by gen_mbhrouts2d.py
 */

#include "fmm2d_c.h"
#include "mbhrouts2d.h"

/* Cross-file calls */
extern void h2cart2polar_(const double *zat, double *r, double *theta);
extern void diffslogbk_fast_(const double *x, const double *beta,
    const double *rscale, double *diffs, const fint *ifders,
    double *ders, double *kvec, const fint *n);
extern void diffslogbk_(const double *x, const double *beta,
    const double *rscale, double *diffs, const fint *n);
extern void diffszkik_fast_(const double *x, const double *beta,
    const double *rscale, double *diffs, const fint *ifders,
    double *ders, double *ivec, const fint *n);
extern void diffszkik_(const double *x, const double *beta,
    const double *rscale, double *diffs, const fint *n);

/* ================================================================
 * mbh2d_rk - compute pow(i) = (r*beta/rscale)^i
 * ================================================================ */
void FNAME(mbh2d_rk)(double *pow, double *dpow,
    const double *r_p, const double *beta_p,
    const double *rscale_p, const fint *nterms_p)
{
    double r = *r_p, beta = *beta_p, rscale = *rscale_p;
    fint nterms = *nterms_p;

    double dtemp2 = (r * beta) / rscale;
    double dtemp1 = 1.0;

    pow[0] = 1.0;
    dpow[0] = 0.0;

    for (fint i = 1; i <= nterms; i++) {
        dpow[i] = i * beta * dtemp1 / rscale;
        dtemp1 = dtemp1 * dtemp2;
        if (dtemp1 > 1.0e250) dtemp1 = 0.0;
        pow[i] = dtemp1;
    }
}

/* ================================================================
 * mbh2d_rksc - compute pow(i) = (r*beta/(2*rscale))^i / i!
 * ================================================================ */
void FNAME(mbh2d_rksc)(double *pow, double *dpow,
    const double *r_p, const double *beta_p,
    const double *rscale_p, const fint *nterms_p)
{
    double r = *r_p, beta = *beta_p, rscale = *rscale_p;
    fint nterms = *nterms_p;

    double dtemp2 = (r * beta) / (2.0 * rscale);
    double dtemp1 = 1.0;

    pow[0] = 1.0;
    dpow[0] = 0.0;

    for (fint i = 1; i <= nterms; i++) {
        dpow[i] = beta * dtemp1 / (2.0 * rscale);
        dtemp1 = dtemp1 * dtemp2 / i;
        if (dtemp1 > 1.0e250) dtemp1 = 0.0;
        pow[i] = dtemp1;
    }
}

/* ================================================================
 * mbh2d_rmk - compute pow(i) = (rscale/(r*beta))^i
 * ================================================================ */
void FNAME(mbh2d_rmk)(double *pow, double *dpow,
    const double *r_p, const double *beta_p,
    const double *rscale_p, const fint *nterms_p)
{
    double r = *r_p, beta = *beta_p, rscale = *rscale_p;
    fint nterms = *nterms_p;

    double dtemp2 = rscale / (r * beta);
    double dtemp1 = dtemp2;

    pow[0] = log(r);
    dpow[0] = 1.0 / r;

    for (fint i = 1; i <= nterms; i++) {
        pow[i] = dtemp1;
        if (dtemp1 < 1.0e-200) dtemp1 = 0.0;
        dtemp1 = dtemp1 * dtemp2;
        dpow[i] = -i * dtemp1 * rscale / beta;
    }
}

/* ================================================================
 * mbh2d_init_carray - initialize binomial coefficient array
 * ================================================================ */
void FNAME(mbh2d_init_carray)(double *carray, const fint *ldc_p)
{
    fint ldc = *ldc_p;
    /* carray is (0:ldc, 0:ldc) */
    fint ld = ldc + 1;

    for (fint l = 0; l <= ldc; l++)
        carray[l] = 1.0; /* carray(l, 0) = 1 */
    for (fint m = 1; m <= ldc; m++) {
        carray[m * ld + m] = 1.0; /* carray(m, m) = 1 */
        for (fint l = m + 1; l <= ldc; l++) {
            carray[m * ld + l] = carray[(m) * ld + (l - 1)]
                               + carray[(m - 1) * ld + (l - 1)];
        }
    }
}

/* ================================================================
 * mbh2dconvtomp_vec
 * ================================================================ */
void FNAME(mbh2dconvtomp_vec)(
    const fint *nd_p, const double *beta_p, const fint *ns_p,
    const fint *ifcharge_p, const double *charge,
    const fint *ifdipole_p, const double *dipstr, const double *dipvec,
    const fint *ifquad_p, const double *quadstr, const double *quadvec,
    const fint *ifoct_p, const double *octstr, const double *octvec,
    const fint *nterms_p, fcomplex *mbhmpole, fcomplex *ympole)
{
    fint nd = *nd_p, ns = *ns_p, nterms = *nterms_p;
    double beta = *beta_p;
    fint ifcharge = *ifcharge_p, ifdipole = *ifdipole_p;
    fint ifquad = *ifquad_p, ifoct = *ifoct_p;
    fcomplex ima = I;
    double pi = 4.0 * atan(1.0);
    fint nt1 = nterms + 1; /* leading dim of 2nd index: 0:nterms -> nterms+1 */

    for (fint i = 1; i <= ns; i++) {
        if (ifcharge == 1) {
            for (fint j = 1; j <= nd; j++) {
                mbhmpole[FA3(j, 0+1, i, nd, nt1)] +=
                    charge[FA2(j, i, nd)] / (2.0 * pi * beta * beta);
            }
        }
        if (ifdipole == 1) {
            for (fint j = 1; j <= nd; j++) {
                mbhmpole[FA3(j, 1+1, i, nd, nt1)] +=
                    dipstr[FA2(j, i, nd)] * (dipvec[FA3(j, 1, i, nd, 2)] +
                    ima * dipvec[FA3(j, 2, i, nd, 2)]) / (2.0 * pi * beta);
            }
        }
        if (ifquad == 1) {
            for (fint j = 1; j <= nd; j++) {
                mbhmpole[FA3(j, 2+1, i, nd, nt1)] +=
                    quadstr[FA2(j, i, nd)] * (quadvec[FA3(j, 1, i, nd, 3)] +
                    quadvec[FA3(j, 2, i, nd, 3)] * ima -
                    quadvec[FA3(j, 3, i, nd, 3)]) / (4.0 * pi);
                ympole[FA3(j, 0+1, i, nd, nt1)] +=
                    quadstr[FA2(j, i, nd)] * (quadvec[FA3(j, 1, i, nd, 3)] +
                    quadvec[FA3(j, 3, i, nd, 3)]) / (4.0 * pi);
            }
        }
        if (ifoct == 1) {
            for (fint j = 1; j <= nd; j++) {
                mbhmpole[FA3(j, 3+1, i, nd, nt1)] +=
                    beta * octstr[FA2(j, i, nd)] * (octvec[FA3(j, 1, i, nd, 4)] +
                    ima * octvec[FA3(j, 2, i, nd, 4)] - octvec[FA3(j, 3, i, nd, 4)] -
                    ima * octvec[FA3(j, 4, i, nd, 4)]) / (8.0 * pi);
                ympole[FA3(j, 1+1, i, nd, nt1)] +=
                    beta * octstr[FA2(j, i, nd)] * (3.0 * octvec[FA3(j, 1, i, nd, 4)] +
                    ima * octvec[FA3(j, 2, i, nd, 4)] + octvec[FA3(j, 3, i, nd, 4)] +
                    3.0 * ima * octvec[FA3(j, 4, i, nd, 4)]) / (8.0 * pi);
            }
        }
    }
}

/* ================================================================
 * mbh2dmpevalp_vec
 * ================================================================ */
void FNAME(mbh2dmpevalp_vec)(
    const fint *nd_p, const double *beta_p, const double *rscale_p,
    const double *center, const fcomplex *mbhmpole, const fcomplex *ympole,
    const fint *nterms_p, const double *ztarg, const fint *ntarg_p,
    double *pot)
{
    fint nd = *nd_p, nterms = *nterms_p, ntarg = *ntarg_p;
    double beta = *beta_p, rscale = *rscale_p;
    fcomplex eye = I;

    fint alloc_sz = nterms + 7;
    fcomplex *mptemp1 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *mptemp2 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    double *diffs = (double *)malloc(alloc_sz * sizeof(double));
    double *kvec = (double *)malloc(alloc_sz * sizeof(double));

    for (fint i = 1; i <= ntarg; i++) {
        double zdiff[2];
        zdiff[0] = ztarg[FA2(1,i,2)] - center[0];
        zdiff[1] = ztarg[FA2(2,i,2)] - center[1];
        double r, theta;
        h2cart2polar_(zdiff, &r, &theta);

        fint ifders = 0;
        double ders_loc[2];
        fint nt2 = nterms + 2;
        diffslogbk_fast_(&r, &beta, &rscale, diffs, &ifders,
                         ders_loc, kvec, &nt2);

        mptemp1[0] = diffs[0];
        mptemp2[0] = kvec[0];
        fcomplex ztemp2 = cexp(eye * theta);
        fcomplex ztemp1 = ztemp2;
        for (fint k = 1; k <= nterms + 2; k++) {
            mptemp1[k] = diffs[k] * creal(ztemp1) + diffs[k] * cimag(ztemp1) * I;
            mptemp2[k] = kvec[k] * creal(ztemp1) + kvec[k] * cimag(ztemp1) * I;
            ztemp1 = ztemp1 * ztemp2;
        }

        /* pot */
        for (fint j = 1; j <= nd; j++) {
            pot[FA2(j,i,nd)] += creal(mptemp1[0]) * creal(mbhmpole[FA2(j,0+1,nd)]);
            pot[FA2(j,i,nd)] += creal(mptemp2[0]) * creal(ympole[FA2(j,0+1,nd)]);
        }
        for (fint l = 1; l <= nterms; l++) {
            for (fint j = 1; j <= nd; j++) {
                pot[FA2(j,i,nd)] += creal(mptemp1[l]) * creal(mbhmpole[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += cimag(mptemp1[l]) * cimag(mbhmpole[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += creal(mptemp2[l]) * creal(ympole[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += cimag(mptemp2[l]) * cimag(ympole[FA2(j,l+1,nd)]);
            }
        }
    }
    free(mptemp1); free(mptemp2); free(diffs); free(kvec);
}

/* ================================================================
 * mbh2dmpevalg_vec
 * ================================================================ */
void FNAME(mbh2dmpevalg_vec)(
    const fint *nd_p, const double *beta_p, const double *rscale_p,
    const double *center, const fcomplex *mbhmpole, const fcomplex *ympole,
    const fint *nterms_p, const double *ztarg, const fint *ntarg_p,
    double *pot, double *grad)
{
    fint nd = *nd_p, nterms = *nterms_p, ntarg = *ntarg_p;
    double beta = *beta_p, rscale = *rscale_p;
    fcomplex eye = I;

    /* gradient derivative expansions: nd x (0:nterms+1) */
    fint gd = nterms + 2;
    fcomplex *ympolex   = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
    fcomplex *ympoley   = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
    fcomplex *mbhmpolex = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
    fcomplex *mbhmpoley = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
#define GI(j, imode) ((imode) * nd + ((j) - 1))

    for (fint j = 1; j <= nd; j++) {
        ympolex[GI(j,1)] = -beta / rscale * ympole[FA2(j, 0+1, nd)];
        ympoley[GI(j,1)] = -beta / rscale * ympole[FA2(j, 0+1, nd)] * eye;
        mbhmpolex[GI(j,1)] = -beta / rscale * mbhmpole[FA2(j, 0+1, nd)];
        mbhmpoley[GI(j,1)] = -beta / rscale * mbhmpole[FA2(j, 0+1, nd)] * eye;
    }
    for (fint ii = 1; ii <= nterms; ii++) {
        for (fint j = 1; j <= nd; j++) {
            ympolex[GI(j,ii-1)] += -beta / 2.0 * ympole[FA2(j, ii+1, nd)] * rscale;
            ympolex[GI(j,ii+1)] += -beta / 2.0 * ympole[FA2(j, ii+1, nd)] / rscale;
            ympoley[GI(j,ii-1)] +=  beta / 2.0 * ympole[FA2(j, ii+1, nd)] * rscale * eye;
            ympoley[GI(j,ii+1)] += -beta / 2.0 * ympole[FA2(j, ii+1, nd)] / rscale * eye;
            ympolex[GI(j,ii-1)]   += -beta / 2.0 * mbhmpole[FA2(j, ii+1, nd)] * rscale;
            mbhmpolex[GI(j,ii+1)] += -beta / 2.0 * mbhmpole[FA2(j, ii+1, nd)] / rscale;
            ympoley[GI(j,ii-1)]   +=  beta / 2.0 * mbhmpole[FA2(j, ii+1, nd)] * rscale * eye;
            mbhmpoley[GI(j,ii+1)] += -beta / 2.0 * mbhmpole[FA2(j, ii+1, nd)] / rscale * eye;
        }
    }

    fint alloc_sz = nterms + 7;
    fcomplex *mptemp1 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *mptemp2 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    double *diffs = (double *)malloc(alloc_sz * sizeof(double));
    double *kvec = (double *)malloc(alloc_sz * sizeof(double));

    for (fint i = 1; i <= ntarg; i++) {
        double zdiff[2];
        zdiff[0] = ztarg[FA2(1,i,2)] - center[0];
        zdiff[1] = ztarg[FA2(2,i,2)] - center[1];
        double r, theta;
        h2cart2polar_(zdiff, &r, &theta);

        fint ifders = 0;
        double ders_loc[2];
        fint nt2 = nterms + 2;
        diffslogbk_fast_(&r, &beta, &rscale, diffs, &ifders,
                         ders_loc, kvec, &nt2);

        mptemp1[0] = diffs[0];
        mptemp2[0] = kvec[0];
        fcomplex ztemp2 = cexp(eye * theta);
        fcomplex ztemp1 = ztemp2;
        for (fint k = 1; k <= nterms + 2; k++) {
            mptemp1[k] = diffs[k] * creal(ztemp1) + diffs[k] * cimag(ztemp1) * I;
            mptemp2[k] = kvec[k] * creal(ztemp1) + kvec[k] * cimag(ztemp1) * I;
            ztemp1 = ztemp1 * ztemp2;
        }

        /* pot */
        for (fint j = 1; j <= nd; j++) {
            pot[FA2(j,i,nd)] += creal(mptemp1[0]) * creal(mbhmpole[FA2(j,0+1,nd)]);
            pot[FA2(j,i,nd)] += creal(mptemp2[0]) * creal(ympole[FA2(j,0+1,nd)]);
        }
        for (fint l = 1; l <= nterms; l++) {
            for (fint j = 1; j <= nd; j++) {
                pot[FA2(j,i,nd)] += creal(mptemp1[l]) * creal(mbhmpole[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += cimag(mptemp1[l]) * cimag(mbhmpole[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += creal(mptemp2[l]) * creal(ympole[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += cimag(mptemp2[l]) * cimag(ympole[FA2(j,l+1,nd)]);
            }
        }

        /* grad */
        for (fint j = 1; j <= nd; j++) {
            grad[FA3(j,1,i,nd,2)] += creal(mptemp1[0]) * creal(mbhmpolex[GI(j,0)]);
            grad[FA3(j,1,i,nd,2)] += creal(mptemp2[0]) * creal(ympolex[GI(j,0)]);
            grad[FA3(j,2,i,nd,2)] += creal(mptemp1[0]) * creal(mbhmpoley[GI(j,0)]);
            grad[FA3(j,2,i,nd,2)] += creal(mptemp2[0]) * creal(ympoley[GI(j,0)]);
        }
        for (fint l = 1; l <= nterms + 1; l++) {
            for (fint j = 1; j <= nd; j++) {
                grad[FA3(j,1,i,nd,2)] += creal(mptemp1[l]) * creal(mbhmpolex[GI(j,l)]);
                grad[FA3(j,1,i,nd,2)] += cimag(mptemp1[l]) * cimag(mbhmpolex[GI(j,l)]);
                grad[FA3(j,1,i,nd,2)] += creal(mptemp2[l]) * creal(ympolex[GI(j,l)]);
                grad[FA3(j,1,i,nd,2)] += cimag(mptemp2[l]) * cimag(ympolex[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += creal(mptemp1[l]) * creal(mbhmpoley[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += cimag(mptemp1[l]) * cimag(mbhmpoley[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += creal(mptemp2[l]) * creal(ympoley[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += cimag(mptemp2[l]) * cimag(ympoley[GI(j,l)]);
            }
        }
    }
    free(mptemp1); free(mptemp2); free(diffs); free(kvec);
    free(ympolex); free(ympoley); free(mbhmpolex); free(mbhmpoley);
#undef GI
}

/* ================================================================
 * mbh2dmpevalh_vec
 * ================================================================ */
void FNAME(mbh2dmpevalh_vec)(
    const fint *nd_p, const double *beta_p, const double *rscale_p,
    const double *center, const fcomplex *mbhmpole, const fcomplex *ympole,
    const fint *nterms_p, const double *ztarg, const fint *ntarg_p,
    double *pot, double *grad, double *hess)
{
    fint nd = *nd_p, nterms = *nterms_p, ntarg = *ntarg_p;
    double beta = *beta_p, rscale = *rscale_p;
    fcomplex eye = I;

    /* gradient derivative expansions: nd x (0:nterms+1) */
    fint gd = nterms + 2;
    fcomplex *ympolex   = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
    fcomplex *ympoley   = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
    fcomplex *mbhmpolex = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
    fcomplex *mbhmpoley = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
#define GI(j, imode) ((imode) * nd + ((j) - 1))

    for (fint j = 1; j <= nd; j++) {
        ympolex[GI(j,1)] = -beta / rscale * ympole[FA2(j, 0+1, nd)];
        ympoley[GI(j,1)] = -beta / rscale * ympole[FA2(j, 0+1, nd)] * eye;
        mbhmpolex[GI(j,1)] = -beta / rscale * mbhmpole[FA2(j, 0+1, nd)];
        mbhmpoley[GI(j,1)] = -beta / rscale * mbhmpole[FA2(j, 0+1, nd)] * eye;
    }
    for (fint ii = 1; ii <= nterms; ii++) {
        for (fint j = 1; j <= nd; j++) {
            ympolex[GI(j,ii-1)] += -beta / 2.0 * ympole[FA2(j, ii+1, nd)] * rscale;
            ympolex[GI(j,ii+1)] += -beta / 2.0 * ympole[FA2(j, ii+1, nd)] / rscale;
            ympoley[GI(j,ii-1)] +=  beta / 2.0 * ympole[FA2(j, ii+1, nd)] * rscale * eye;
            ympoley[GI(j,ii+1)] += -beta / 2.0 * ympole[FA2(j, ii+1, nd)] / rscale * eye;
            ympolex[GI(j,ii-1)]   += -beta / 2.0 * mbhmpole[FA2(j, ii+1, nd)] * rscale;
            mbhmpolex[GI(j,ii+1)] += -beta / 2.0 * mbhmpole[FA2(j, ii+1, nd)] / rscale;
            ympoley[GI(j,ii-1)]   +=  beta / 2.0 * mbhmpole[FA2(j, ii+1, nd)] * rscale * eye;
            mbhmpoley[GI(j,ii+1)] += -beta / 2.0 * mbhmpole[FA2(j, ii+1, nd)] / rscale * eye;
        }
    }

    /* hessian derivative expansions: nd x (0:nterms+2) */
    fint hd = nterms + 3;
    fcomplex *ympolexx   = (fcomplex *)calloc(nd * hd, sizeof(fcomplex));
    fcomplex *ympolexy   = (fcomplex *)calloc(nd * hd, sizeof(fcomplex));
    fcomplex *ympoleyy   = (fcomplex *)calloc(nd * hd, sizeof(fcomplex));
    fcomplex *mbhmpolexx = (fcomplex *)calloc(nd * hd, sizeof(fcomplex));
    fcomplex *mbhmpolexy = (fcomplex *)calloc(nd * hd, sizeof(fcomplex));
    fcomplex *mbhmpoleyy = (fcomplex *)calloc(nd * hd, sizeof(fcomplex));
#define HI(j, imode) ((imode) * nd + ((j) - 1))

    for (fint j = 1; j <= nd; j++) {
        ympolexx[HI(j,1)]   = -beta / 1.0 / rscale * creal(ympolex[GI(j,0)]);
        ympolexy[HI(j,1)]   = -beta / 1.0 / rscale * creal(ympolex[GI(j,0)]) * eye;
        ympoleyy[HI(j,1)]   = -beta / 1.0 / rscale * creal(ympoley[GI(j,0)]) * eye;
        mbhmpolexx[HI(j,1)] = -beta / 1.0 / rscale * creal(mbhmpolex[GI(j,0)]);
        mbhmpolexy[HI(j,1)] = -beta / 1.0 / rscale * creal(mbhmpolex[GI(j,0)]) * eye;
        mbhmpoleyy[HI(j,1)] = -beta / 1.0 / rscale * creal(mbhmpoley[GI(j,0)]) * eye;
    }
    for (fint ii = 1; ii <= nterms + 1; ii++) {
        for (fint j = 1; j <= nd; j++) {
            ympolexx[HI(j,ii-1)] += -beta/2.0*ympolex[GI(j,ii)]*rscale;
            ympolexx[HI(j,ii+1)] += -beta/2.0*ympolex[GI(j,ii)]/rscale;
            ympolexy[HI(j,ii-1)] +=  beta/2.0*ympolex[GI(j,ii)]*rscale*eye;
            ympolexy[HI(j,ii+1)] += -beta/2.0*ympolex[GI(j,ii)]/rscale*eye;
            ympoleyy[HI(j,ii-1)] +=  beta/2.0*ympoley[GI(j,ii)]*rscale*eye;
            ympoleyy[HI(j,ii+1)] += -beta/2.0*ympoley[GI(j,ii)]/rscale*eye;
            ympolexx[HI(j,ii-1)]   += -beta/2.0*mbhmpolex[GI(j,ii)]*rscale;
            mbhmpolexx[HI(j,ii+1)] += -beta/2.0*mbhmpolex[GI(j,ii)]/rscale;
            ympolexy[HI(j,ii-1)]   +=  beta/2.0*mbhmpolex[GI(j,ii)]*rscale*eye;
            mbhmpolexy[HI(j,ii+1)] += -beta/2.0*mbhmpolex[GI(j,ii)]/rscale*eye;
            ympoleyy[HI(j,ii-1)]   +=  beta/2.0*mbhmpoley[GI(j,ii)]*rscale*eye;
            mbhmpoleyy[HI(j,ii+1)] += -beta/2.0*mbhmpoley[GI(j,ii)]/rscale*eye;
        }
    }

    fint alloc_sz = nterms + 7;
    fcomplex *mptemp1 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *mptemp2 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    double *diffs = (double *)malloc(alloc_sz * sizeof(double));
    double *kvec = (double *)malloc(alloc_sz * sizeof(double));

    for (fint i = 1; i <= ntarg; i++) {
        double zdiff[2];
        zdiff[0] = ztarg[FA2(1,i,2)] - center[0];
        zdiff[1] = ztarg[FA2(2,i,2)] - center[1];
        double r, theta;
        h2cart2polar_(zdiff, &r, &theta);

        fint ifders = 0;
        double ders_loc[2];
        fint nt2 = nterms + 2;
        diffslogbk_fast_(&r, &beta, &rscale, diffs, &ifders,
                         ders_loc, kvec, &nt2);

        mptemp1[0] = diffs[0];
        mptemp2[0] = kvec[0];
        fcomplex ztemp2 = cexp(eye * theta);
        fcomplex ztemp1 = ztemp2;
        for (fint k = 1; k <= nterms + 2; k++) {
            mptemp1[k] = diffs[k] * creal(ztemp1) + diffs[k] * cimag(ztemp1) * I;
            mptemp2[k] = kvec[k] * creal(ztemp1) + kvec[k] * cimag(ztemp1) * I;
            ztemp1 = ztemp1 * ztemp2;
        }

        /* pot */
        for (fint j = 1; j <= nd; j++) {
            pot[FA2(j,i,nd)] += creal(mptemp1[0]) * creal(mbhmpole[FA2(j,0+1,nd)]);
            pot[FA2(j,i,nd)] += creal(mptemp2[0]) * creal(ympole[FA2(j,0+1,nd)]);
        }
        for (fint l = 1; l <= nterms; l++) {
            for (fint j = 1; j <= nd; j++) {
                pot[FA2(j,i,nd)] += creal(mptemp1[l]) * creal(mbhmpole[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += cimag(mptemp1[l]) * cimag(mbhmpole[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += creal(mptemp2[l]) * creal(ympole[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += cimag(mptemp2[l]) * cimag(ympole[FA2(j,l+1,nd)]);
            }
        }

        /* grad */
        for (fint j = 1; j <= nd; j++) {
            grad[FA3(j,1,i,nd,2)] += creal(mptemp1[0]) * creal(mbhmpolex[GI(j,0)]);
            grad[FA3(j,1,i,nd,2)] += creal(mptemp2[0]) * creal(ympolex[GI(j,0)]);
            grad[FA3(j,2,i,nd,2)] += creal(mptemp1[0]) * creal(mbhmpoley[GI(j,0)]);
            grad[FA3(j,2,i,nd,2)] += creal(mptemp2[0]) * creal(ympoley[GI(j,0)]);
        }
        for (fint l = 1; l <= nterms + 1; l++) {
            for (fint j = 1; j <= nd; j++) {
                grad[FA3(j,1,i,nd,2)] += creal(mptemp1[l]) * creal(mbhmpolex[GI(j,l)]);
                grad[FA3(j,1,i,nd,2)] += cimag(mptemp1[l]) * cimag(mbhmpolex[GI(j,l)]);
                grad[FA3(j,1,i,nd,2)] += creal(mptemp2[l]) * creal(ympolex[GI(j,l)]);
                grad[FA3(j,1,i,nd,2)] += cimag(mptemp2[l]) * cimag(ympolex[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += creal(mptemp1[l]) * creal(mbhmpoley[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += cimag(mptemp1[l]) * cimag(mbhmpoley[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += creal(mptemp2[l]) * creal(ympoley[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += cimag(mptemp2[l]) * cimag(ympoley[GI(j,l)]);
            }
        }

        /* hess */
        for (fint j = 1; j <= nd; j++) {
            hess[FA3(j,1,i,nd,3)] += creal(mptemp1[0]) * creal(mbhmpolexx[HI(j,0)]);
            hess[FA3(j,1,i,nd,3)] += creal(mptemp2[0]) * creal(ympolexx[HI(j,0)]);
            hess[FA3(j,2,i,nd,3)] += creal(mptemp1[0]) * creal(mbhmpolexy[HI(j,0)]);
            hess[FA3(j,2,i,nd,3)] += creal(mptemp2[0]) * creal(ympolexy[HI(j,0)]);
            hess[FA3(j,3,i,nd,3)] += creal(mptemp1[0]) * creal(mbhmpoleyy[HI(j,0)]);
            hess[FA3(j,3,i,nd,3)] += creal(mptemp2[0]) * creal(ympoleyy[HI(j,0)]);
        }
        for (fint l = 1; l <= nterms + 1; l++) {
            for (fint j = 1; j <= nd; j++) {
                hess[FA3(j,1,i,nd,3)] += creal(mptemp1[l]) * creal(mbhmpolexx[HI(j,l)]);
                hess[FA3(j,1,i,nd,3)] += cimag(mptemp1[l]) * cimag(mbhmpolexx[HI(j,l)]);
                hess[FA3(j,1,i,nd,3)] += creal(mptemp2[l]) * creal(ympolexx[HI(j,l)]);
                hess[FA3(j,1,i,nd,3)] += cimag(mptemp2[l]) * cimag(ympolexx[HI(j,l)]);
                hess[FA3(j,2,i,nd,3)] += creal(mptemp1[l]) * creal(mbhmpolexy[HI(j,l)]);
                hess[FA3(j,2,i,nd,3)] += cimag(mptemp1[l]) * cimag(mbhmpolexy[HI(j,l)]);
                hess[FA3(j,2,i,nd,3)] += creal(mptemp2[l]) * creal(ympolexy[HI(j,l)]);
                hess[FA3(j,2,i,nd,3)] += cimag(mptemp2[l]) * cimag(ympolexy[HI(j,l)]);
                hess[FA3(j,3,i,nd,3)] += creal(mptemp1[l]) * creal(mbhmpoleyy[HI(j,l)]);
                hess[FA3(j,3,i,nd,3)] += cimag(mptemp1[l]) * cimag(mbhmpoleyy[HI(j,l)]);
                hess[FA3(j,3,i,nd,3)] += creal(mptemp2[l]) * creal(ympoleyy[HI(j,l)]);
                hess[FA3(j,3,i,nd,3)] += cimag(mptemp2[l]) * cimag(ympoleyy[HI(j,l)]);
            }
        }
    }
    free(mptemp1); free(mptemp2); free(diffs); free(kvec);
    free(ympolex); free(ympoley); free(mbhmpolex); free(mbhmpoley);
#undef GI
    free(ympolexx); free(ympolexy); free(ympoleyy);
    free(mbhmpolexx); free(mbhmpolexy); free(mbhmpoleyy);
#undef HI
}

/* ================================================================
 * mbh2dtaevalp_vec
 * ================================================================ */
void FNAME(mbh2dtaevalp_vec)(
    const fint *nd_p, const double *beta_p, const double *rscale_p,
    const double *center, const fcomplex *mbhloc, const fcomplex *lloc,
    const fint *nterms_p, const double *ztarg, const fint *ntarg_p,
    double *pot)
{
    fint nd = *nd_p, nterms = *nterms_p, ntarg = *ntarg_p;
    double beta = *beta_p, rscale = *rscale_p;
    fcomplex eye = I;

    fint alloc_sz = nterms + 7;
    double *pow_arr = (double *)malloc(alloc_sz * sizeof(double));
    double *dpow = (double *)malloc(alloc_sz * sizeof(double));
    fcomplex *mptemp1 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *mptemp2 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    double *diffs = (double *)malloc(alloc_sz * sizeof(double));
    double ivec[201];

    for (fint i = 1; i <= ntarg; i++) {
        double zdiff[2];
        zdiff[0] = ztarg[FA2(1,i,2)] - center[0];
        zdiff[1] = ztarg[FA2(2,i,2)] - center[1];
        double r, theta;
        h2cart2polar_(zdiff, &r, &theta);

        fint nt2 = nterms + 2;
        FNAME(mbh2d_rk)(pow_arr, dpow, &r, &beta, &rscale, &nt2);

        fint ifders = 0;
        double ders_loc[2];
        diffszkik_fast_(&r, &beta, &rscale, diffs, &ifders,
                        ders_loc, ivec, &nt2);

        mptemp1[0] = diffs[0];
        mptemp2[0] = pow_arr[0];
        fcomplex ztemp2 = cexp(eye * theta);
        fcomplex ztemp1 = ztemp2;
        for (fint k = 1; k <= nterms + 2; k++) {
            mptemp1[k] = diffs[k] * creal(ztemp1) + diffs[k] * cimag(ztemp1) * I;
            mptemp2[k] = pow_arr[k] * creal(ztemp1) + pow_arr[k] * cimag(ztemp1) * I;
            ztemp1 = ztemp1 * ztemp2;
        }

        /* pot */
        for (fint j = 1; j <= nd; j++) {
            pot[FA2(j,i,nd)] += creal(mptemp1[0]) * creal(mbhloc[FA2(j,0+1,nd)]);
            pot[FA2(j,i,nd)] += creal(mptemp2[0]) * creal(lloc[FA2(j,0+1,nd)]);
        }
        for (fint l = 1; l <= nterms; l++) {
            for (fint j = 1; j <= nd; j++) {
                pot[FA2(j,i,nd)] += creal(mptemp1[l]) * creal(mbhloc[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += cimag(mptemp1[l]) * cimag(mbhloc[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += creal(mptemp2[l]) * creal(lloc[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += cimag(mptemp2[l]) * cimag(lloc[FA2(j,l+1,nd)]);
            }
        }
    }
    free(pow_arr); free(dpow); free(mptemp1); free(mptemp2); free(diffs);
}

/* ================================================================
 * mbh2dtaevalg_vec
 * ================================================================ */
void FNAME(mbh2dtaevalg_vec)(
    const fint *nd_p, const double *beta_p, const double *rscale_p,
    const double *center, const fcomplex *mbhloc, const fcomplex *lloc,
    const fint *nterms_p, const double *ztarg, const fint *ntarg_p,
    double *pot, double *grad)
{
    fint nd = *nd_p, nterms = *nterms_p, ntarg = *ntarg_p;
    double beta = *beta_p, rscale = *rscale_p;
    fcomplex eye = I;

    fint gd = nterms + 2;
    fcomplex *mbhlocx = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
    fcomplex *mbhlocy = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
    fcomplex *llocx   = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
    fcomplex *llocy   = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
#define GI(j, imode) ((imode) * nd + ((j) - 1))

    double dtemp = 1.0 / 2.0;
    for (fint j = 1; j <= nd; j++) {
        mbhlocx[GI(j,1)] = creal(mbhloc[FA2(j,0+1,nd)]) * beta * rscale;
        mbhlocy[GI(j,1)] = creal(mbhloc[FA2(j,0+1,nd)]) * beta * rscale * eye;
        llocx[GI(j,1)] = creal(mbhloc[FA2(j,0+1,nd)]) * beta * dtemp * rscale;
        llocy[GI(j,1)] = creal(mbhloc[FA2(j,0+1,nd)]) * beta * dtemp * rscale * eye;
    }
    for (fint ii = 1; ii <= nterms; ii++) {
        dtemp = dtemp / (2 * (ii + 1));
        for (fint j = 1; j <= nd; j++) {
            mbhlocx[GI(j,ii-1)] += beta / 2 / rscale * mbhloc[FA2(j,ii+1,nd)];
            mbhlocx[GI(j,ii+1)] += beta / 2 * rscale * mbhloc[FA2(j,ii+1,nd)];
            mbhlocy[GI(j,ii-1)] += -beta / 2 * eye / rscale * mbhloc[FA2(j,ii+1,nd)];
            mbhlocy[GI(j,ii+1)] +=  beta / 2 * eye * rscale * mbhloc[FA2(j,ii+1,nd)];
            llocx[GI(j,ii-1)] += beta * ii / rscale * lloc[FA2(j,ii+1,nd)];
            llocy[GI(j,ii-1)] += -beta * ii * eye / rscale * lloc[FA2(j,ii+1,nd)];
            llocx[GI(j,ii+1)] += beta / 2 * rscale * mbhloc[FA2(j,ii+1,nd)] * dtemp;
            llocy[GI(j,ii+1)] += beta / 2 * eye * rscale * mbhloc[FA2(j,ii+1,nd)] * dtemp;
        }
    }

    fint alloc_sz = nterms + 7;
    double *pow_arr = (double *)malloc(alloc_sz * sizeof(double));
    double *dpow = (double *)malloc(alloc_sz * sizeof(double));
    fcomplex *mptemp1 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *mptemp2 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    double *diffs = (double *)malloc(alloc_sz * sizeof(double));
    double ivec[201];

    for (fint i = 1; i <= ntarg; i++) {
        double zdiff[2];
        zdiff[0] = ztarg[FA2(1,i,2)] - center[0];
        zdiff[1] = ztarg[FA2(2,i,2)] - center[1];
        double r, theta;
        h2cart2polar_(zdiff, &r, &theta);

        fint nt2 = nterms + 2;
        FNAME(mbh2d_rk)(pow_arr, dpow, &r, &beta, &rscale, &nt2);

        fint ifders = 0;
        double ders_loc[2];
        diffszkik_fast_(&r, &beta, &rscale, diffs, &ifders,
                        ders_loc, ivec, &nt2);

        mptemp1[0] = diffs[0];
        mptemp2[0] = pow_arr[0];
        fcomplex ztemp2 = cexp(eye * theta);
        fcomplex ztemp1 = ztemp2;
        for (fint k = 1; k <= nterms + 2; k++) {
            mptemp1[k] = diffs[k] * creal(ztemp1) + diffs[k] * cimag(ztemp1) * I;
            mptemp2[k] = pow_arr[k] * creal(ztemp1) + pow_arr[k] * cimag(ztemp1) * I;
            ztemp1 = ztemp1 * ztemp2;
        }

        /* pot */
        for (fint j = 1; j <= nd; j++) {
            pot[FA2(j,i,nd)] += creal(mptemp1[0]) * creal(mbhloc[FA2(j,0+1,nd)]);
            pot[FA2(j,i,nd)] += creal(mptemp2[0]) * creal(lloc[FA2(j,0+1,nd)]);
        }
        for (fint l = 1; l <= nterms; l++) {
            for (fint j = 1; j <= nd; j++) {
                pot[FA2(j,i,nd)] += creal(mptemp1[l]) * creal(mbhloc[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += cimag(mptemp1[l]) * cimag(mbhloc[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += creal(mptemp2[l]) * creal(lloc[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += cimag(mptemp2[l]) * cimag(lloc[FA2(j,l+1,nd)]);
            }
        }

        /* grad */
        for (fint j = 1; j <= nd; j++) {
            grad[FA3(j,1,i,nd,2)] += creal(mptemp1[0]) * creal(mbhlocx[GI(j,0)]);
            grad[FA3(j,1,i,nd,2)] += creal(mptemp2[0]) * creal(llocx[GI(j,0)]);
            grad[FA3(j,2,i,nd,2)] += creal(mptemp1[0]) * creal(mbhlocy[GI(j,0)]);
            grad[FA3(j,2,i,nd,2)] += creal(mptemp2[0]) * creal(llocy[GI(j,0)]);
        }
        for (fint l = 1; l <= nterms + 1; l++) {
            for (fint j = 1; j <= nd; j++) {
                grad[FA3(j,1,i,nd,2)] += creal(mptemp1[l]) * creal(mbhlocx[GI(j,l)]);
                grad[FA3(j,1,i,nd,2)] += cimag(mptemp1[l]) * cimag(mbhlocx[GI(j,l)]);
                grad[FA3(j,1,i,nd,2)] += creal(mptemp2[l]) * creal(llocx[GI(j,l)]);
                grad[FA3(j,1,i,nd,2)] += cimag(mptemp2[l]) * cimag(llocx[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += creal(mptemp1[l]) * creal(mbhlocy[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += cimag(mptemp1[l]) * cimag(mbhlocy[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += creal(mptemp2[l]) * creal(llocy[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += cimag(mptemp2[l]) * cimag(llocy[GI(j,l)]);
            }
        }
    }
    free(pow_arr); free(dpow); free(mptemp1); free(mptemp2); free(diffs);
    free(mbhlocx); free(mbhlocy); free(llocx); free(llocy);
#undef GI
}

/* ================================================================
 * mbh2dtaevalh_vec
 * ================================================================ */
void FNAME(mbh2dtaevalh_vec)(
    const fint *nd_p, const double *beta_p, const double *rscale_p,
    const double *center, const fcomplex *mbhloc, const fcomplex *lloc,
    const fint *nterms_p, const double *ztarg, const fint *ntarg_p,
    double *pot, double *grad, double *hess)
{
    fint nd = *nd_p, nterms = *nterms_p, ntarg = *ntarg_p;
    double beta = *beta_p, rscale = *rscale_p;
    fcomplex eye = I;

    fint gd = nterms + 2;
    fcomplex *mbhlocx = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
    fcomplex *mbhlocy = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
    fcomplex *llocx   = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
    fcomplex *llocy   = (fcomplex *)calloc(nd * gd, sizeof(fcomplex));
#define GI(j, imode) ((imode) * nd + ((j) - 1))

    double dtemp = 1.0 / 2.0;
    for (fint j = 1; j <= nd; j++) {
        mbhlocx[GI(j,1)] = creal(mbhloc[FA2(j,0+1,nd)]) * beta * rscale;
        mbhlocy[GI(j,1)] = creal(mbhloc[FA2(j,0+1,nd)]) * beta * rscale * eye;
        llocx[GI(j,1)] = creal(mbhloc[FA2(j,0+1,nd)]) * beta * dtemp * rscale;
        llocy[GI(j,1)] = creal(mbhloc[FA2(j,0+1,nd)]) * beta * dtemp * rscale * eye;
    }
    for (fint ii = 1; ii <= nterms; ii++) {
        dtemp = dtemp / (2 * (ii + 1));
        for (fint j = 1; j <= nd; j++) {
            mbhlocx[GI(j,ii-1)] += beta / 2 / rscale * mbhloc[FA2(j,ii+1,nd)];
            mbhlocx[GI(j,ii+1)] += beta / 2 * rscale * mbhloc[FA2(j,ii+1,nd)];
            mbhlocy[GI(j,ii-1)] += -beta / 2 * eye / rscale * mbhloc[FA2(j,ii+1,nd)];
            mbhlocy[GI(j,ii+1)] +=  beta / 2 * eye * rscale * mbhloc[FA2(j,ii+1,nd)];
            llocx[GI(j,ii-1)] += beta * ii / rscale * lloc[FA2(j,ii+1,nd)];
            llocy[GI(j,ii-1)] += -beta * ii * eye / rscale * lloc[FA2(j,ii+1,nd)];
            llocx[GI(j,ii+1)] += beta / 2 * rscale * mbhloc[FA2(j,ii+1,nd)] * dtemp;
            llocy[GI(j,ii+1)] += beta / 2 * eye * rscale * mbhloc[FA2(j,ii+1,nd)] * dtemp;
        }
    }

    fint hd = nterms + 3;
    fcomplex *mbhlocxx = (fcomplex *)calloc(nd * hd, sizeof(fcomplex));
    fcomplex *mbhlocxy = (fcomplex *)calloc(nd * hd, sizeof(fcomplex));
    fcomplex *mbhlocyy = (fcomplex *)calloc(nd * hd, sizeof(fcomplex));
    fcomplex *llocxx   = (fcomplex *)calloc(nd * hd, sizeof(fcomplex));
    fcomplex *llocxy   = (fcomplex *)calloc(nd * hd, sizeof(fcomplex));
    fcomplex *llocyy   = (fcomplex *)calloc(nd * hd, sizeof(fcomplex));
#define HI(j, imode) ((imode) * nd + ((j) - 1))

    dtemp = 1.0 / 2.0;
    for (fint j = 1; j <= nd; j++) {
        mbhlocxx[HI(j,1)] = creal(mbhlocx[GI(j,0)]) * beta * rscale;
        mbhlocxy[HI(j,1)] = creal(mbhlocx[GI(j,0)]) * beta * rscale * eye;
        mbhlocyy[HI(j,1)] = creal(mbhlocy[GI(j,0)]) * beta * rscale * eye;
        llocxx[HI(j,1)] = creal(mbhlocx[GI(j,0)]) * beta * dtemp * rscale;
        llocxy[HI(j,1)] = creal(mbhlocx[GI(j,0)]) * beta * dtemp * rscale * eye;
        llocyy[HI(j,1)] = creal(mbhlocy[GI(j,0)]) * beta * dtemp * rscale * eye;
    }
    for (fint ii = 1; ii <= nterms + 1; ii++) {
        dtemp = dtemp / (2 * (ii + 1));
        for (fint j = 1; j <= nd; j++) {
            mbhlocxx[HI(j,ii-1)] += beta/2/rscale * mbhlocx[GI(j,ii)];
            mbhlocxx[HI(j,ii+1)] += beta/2*rscale * mbhlocx[GI(j,ii)];
            mbhlocxy[HI(j,ii-1)] += -beta/2*eye/rscale * mbhlocx[GI(j,ii)];
            mbhlocxy[HI(j,ii+1)] +=  beta/2*eye*rscale * mbhlocx[GI(j,ii)];
            mbhlocyy[HI(j,ii-1)] += -beta/2*eye/rscale * mbhlocy[GI(j,ii)];
            mbhlocyy[HI(j,ii+1)] +=  beta/2*eye*rscale * mbhlocy[GI(j,ii)];
            llocxx[HI(j,ii-1)] += beta*ii/rscale * llocx[GI(j,ii)];
            llocxy[HI(j,ii-1)] += -beta*ii*eye/rscale * llocx[GI(j,ii)];
            llocyy[HI(j,ii-1)] += -beta*ii*eye/rscale * llocy[GI(j,ii)];
            llocxx[HI(j,ii+1)] += beta/2*rscale * mbhlocx[GI(j,ii)] * dtemp;
            llocxy[HI(j,ii+1)] += beta/2*eye*rscale * mbhlocx[GI(j,ii)] * dtemp;
            llocyy[HI(j,ii+1)] += beta/2*eye*rscale * mbhlocy[GI(j,ii)] * dtemp;
        }
    }

    fint alloc_sz = nterms + 7;
    double *pow_arr = (double *)malloc(alloc_sz * sizeof(double));
    double *dpow = (double *)malloc(alloc_sz * sizeof(double));
    fcomplex *mptemp1 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *mptemp2 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    double *diffs = (double *)malloc(alloc_sz * sizeof(double));
    double ivec[201];

    for (fint i = 1; i <= ntarg; i++) {
        double zdiff[2];
        zdiff[0] = ztarg[FA2(1,i,2)] - center[0];
        zdiff[1] = ztarg[FA2(2,i,2)] - center[1];
        double r, theta;
        h2cart2polar_(zdiff, &r, &theta);

        fint nt2 = nterms + 2;
        FNAME(mbh2d_rk)(pow_arr, dpow, &r, &beta, &rscale, &nt2);

        fint ifders = 0;
        double ders_loc[2];
        diffszkik_fast_(&r, &beta, &rscale, diffs, &ifders,
                        ders_loc, ivec, &nt2);

        mptemp1[0] = diffs[0];
        mptemp2[0] = pow_arr[0];
        fcomplex ztemp2 = cexp(eye * theta);
        fcomplex ztemp1 = ztemp2;
        for (fint k = 1; k <= nterms + 2; k++) {
            mptemp1[k] = diffs[k] * creal(ztemp1) + diffs[k] * cimag(ztemp1) * I;
            mptemp2[k] = pow_arr[k] * creal(ztemp1) + pow_arr[k] * cimag(ztemp1) * I;
            ztemp1 = ztemp1 * ztemp2;
        }

        /* pot */
        for (fint j = 1; j <= nd; j++) {
            pot[FA2(j,i,nd)] += creal(mptemp1[0]) * creal(mbhloc[FA2(j,0+1,nd)]);
            pot[FA2(j,i,nd)] += creal(mptemp2[0]) * creal(lloc[FA2(j,0+1,nd)]);
        }
        for (fint l = 1; l <= nterms; l++) {
            for (fint j = 1; j <= nd; j++) {
                pot[FA2(j,i,nd)] += creal(mptemp1[l]) * creal(mbhloc[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += cimag(mptemp1[l]) * cimag(mbhloc[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += creal(mptemp2[l]) * creal(lloc[FA2(j,l+1,nd)]);
                pot[FA2(j,i,nd)] += cimag(mptemp2[l]) * cimag(lloc[FA2(j,l+1,nd)]);
            }
        }

        /* grad */
        for (fint j = 1; j <= nd; j++) {
            grad[FA3(j,1,i,nd,2)] += creal(mptemp1[0]) * creal(mbhlocx[GI(j,0)]);
            grad[FA3(j,1,i,nd,2)] += creal(mptemp2[0]) * creal(llocx[GI(j,0)]);
            grad[FA3(j,2,i,nd,2)] += creal(mptemp1[0]) * creal(mbhlocy[GI(j,0)]);
            grad[FA3(j,2,i,nd,2)] += creal(mptemp2[0]) * creal(llocy[GI(j,0)]);
        }
        for (fint l = 1; l <= nterms + 1; l++) {
            for (fint j = 1; j <= nd; j++) {
                grad[FA3(j,1,i,nd,2)] += creal(mptemp1[l]) * creal(mbhlocx[GI(j,l)]);
                grad[FA3(j,1,i,nd,2)] += cimag(mptemp1[l]) * cimag(mbhlocx[GI(j,l)]);
                grad[FA3(j,1,i,nd,2)] += creal(mptemp2[l]) * creal(llocx[GI(j,l)]);
                grad[FA3(j,1,i,nd,2)] += cimag(mptemp2[l]) * cimag(llocx[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += creal(mptemp1[l]) * creal(mbhlocy[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += cimag(mptemp1[l]) * cimag(mbhlocy[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += creal(mptemp2[l]) * creal(llocy[GI(j,l)]);
                grad[FA3(j,2,i,nd,2)] += cimag(mptemp2[l]) * cimag(llocy[GI(j,l)]);
            }
        }

        /* hess */
        for (fint j = 1; j <= nd; j++) {
            hess[FA3(j,1,i,nd,3)] += creal(mptemp1[0]) * creal(mbhlocxx[HI(j,0)]);
            hess[FA3(j,1,i,nd,3)] += creal(mptemp2[0]) * creal(llocxx[HI(j,0)]);
            hess[FA3(j,2,i,nd,3)] += creal(mptemp1[0]) * creal(mbhlocxy[HI(j,0)]);
            hess[FA3(j,2,i,nd,3)] += creal(mptemp2[0]) * creal(llocxy[HI(j,0)]);
            hess[FA3(j,3,i,nd,3)] += creal(mptemp1[0]) * creal(mbhlocyy[HI(j,0)]);
            hess[FA3(j,3,i,nd,3)] += creal(mptemp2[0]) * creal(llocyy[HI(j,0)]);
        }
        for (fint l = 1; l <= nterms + 1; l++) {
            for (fint j = 1; j <= nd; j++) {
                hess[FA3(j,1,i,nd,3)] += creal(mptemp1[l]) * creal(mbhlocxx[HI(j,l)]);
                hess[FA3(j,1,i,nd,3)] += cimag(mptemp1[l]) * cimag(mbhlocxx[HI(j,l)]);
                hess[FA3(j,1,i,nd,3)] += creal(mptemp2[l]) * creal(llocxx[HI(j,l)]);
                hess[FA3(j,1,i,nd,3)] += cimag(mptemp2[l]) * cimag(llocxx[HI(j,l)]);
                hess[FA3(j,2,i,nd,3)] += creal(mptemp1[l]) * creal(mbhlocxy[HI(j,l)]);
                hess[FA3(j,2,i,nd,3)] += cimag(mptemp1[l]) * cimag(mbhlocxy[HI(j,l)]);
                hess[FA3(j,2,i,nd,3)] += creal(mptemp2[l]) * creal(llocxy[HI(j,l)]);
                hess[FA3(j,2,i,nd,3)] += cimag(mptemp2[l]) * cimag(llocxy[HI(j,l)]);
                hess[FA3(j,3,i,nd,3)] += creal(mptemp1[l]) * creal(mbhlocyy[HI(j,l)]);
                hess[FA3(j,3,i,nd,3)] += cimag(mptemp1[l]) * cimag(mbhlocyy[HI(j,l)]);
                hess[FA3(j,3,i,nd,3)] += creal(mptemp2[l]) * creal(llocyy[HI(j,l)]);
                hess[FA3(j,3,i,nd,3)] += cimag(mptemp2[l]) * cimag(llocyy[HI(j,l)]);
            }
        }
    }
    free(pow_arr); free(dpow); free(mptemp1); free(mptemp2); free(diffs);
    free(mbhlocx); free(mbhlocy); free(llocx); free(llocy);
#undef GI
    free(mbhlocxx); free(mbhlocxy); free(mbhlocyy);
    free(llocxx); free(llocxy); free(llocyy);
#undef HI
}

/* ================================================================
 * mbh2dformmpmp_vec
 * ================================================================ */
void FNAME(mbh2dformmpmp_vec)(
    const fint *nd_p, const double *beta_p, const double *rscale_p,
    const double *source, const fint *ns_p,
    fcomplex *mbhmpolesrc, fcomplex *ympolesrc,
    const fint *ntermsrc_p, const double *center,
    const fint *nterms_p, fcomplex *mbhmpole, fcomplex *ympole)
{
    fint nd = *nd_p, ns = *ns_p, ntermsrc = *ntermsrc_p, nterms = *nterms_p;
    double rscale = *rscale_p;
    double rscale1 = rscale;
    fint nt1_src = ntermsrc + 1;

    for (fint i = 1; i <= ns; i++) {
        double rsc = 1;
        for (fint j = 0; j <= ntermsrc; j++) {
            for (fint l = 1; l <= nd; l++) {
                mbhmpolesrc[FA3(l, j+1, i, nd, nt1_src)] /= rsc;
                ympolesrc[FA3(l, j+1, i, nd, nt1_src)] /= rsc;
            }
            rsc *= rscale1;
        }

        FNAME(mbh2dmpmp_vec)(nd_p, beta_p, &rscale1,
            &source[FA2(1, i, 2) /* 2*(i-1) */],
            &mbhmpolesrc[FA3(1, 0+1, i, nd, nt1_src)],
            &ympolesrc[FA3(1, 0+1, i, nd, nt1_src)],
            ntermsrc_p, rscale_p, center, mbhmpole, ympole, nterms_p);

        rsc = 1;
        for (fint j = 0; j <= ntermsrc; j++) {
            for (fint l = 1; l <= nd; l++) {
                mbhmpolesrc[FA3(l, j+1, i, nd, nt1_src)] /= rsc;
                ympolesrc[FA3(l, j+1, i, nd, nt1_src)] /= rsc;
            }
            rsc /= rscale1;
        }
    }
}

/* ================================================================
 * mbh2dformtamp_vec
 * ================================================================ */
void FNAME(mbh2dformtamp_vec)(
    const fint *nd_p, const double *beta_p, const double *rscale_p,
    const double *source, const fint *ns_p,
    fcomplex *mbhmpolesrc, fcomplex *ympolesrc,
    const fint *ntermsrc_p, const double *center,
    const fint *nterms_p, fcomplex *mbhloc, fcomplex *lloc)
{
    fint nd = *nd_p, ns = *ns_p, ntermsrc = *ntermsrc_p;
    double rscale = *rscale_p;
    double rscale1 = rscale;
    fint nt1_src = ntermsrc + 1;

    for (fint i = 1; i <= ns; i++) {
        double rsc = 1;
        for (fint j = 0; j <= ntermsrc; j++) {
            for (fint l = 1; l <= nd; l++) {
                mbhmpolesrc[FA3(l, j+1, i, nd, nt1_src)] /= rsc;
                ympolesrc[FA3(l, j+1, i, nd, nt1_src)] /= rsc;
            }
            rsc *= rscale1;
        }

        FNAME(mbh2dmploc_vec)(nd_p, beta_p, &rscale1,
            &source[FA2(1, i, 2)],
            &mbhmpolesrc[FA3(1, 0+1, i, nd, nt1_src)],
            &ympolesrc[FA3(1, 0+1, i, nd, nt1_src)],
            ntermsrc_p, rscale_p, center, mbhloc, lloc, nterms_p);

        rsc = 1;
        for (fint j = 0; j <= ntermsrc; j++) {
            for (fint l = 1; l <= nd; l++) {
                mbhmpolesrc[FA3(l, j+1, i, nd, nt1_src)] /= rsc;
                ympolesrc[FA3(l, j+1, i, nd, nt1_src)] /= rsc;
            }
            rsc /= rscale1;
        }
    }
}

/* ================================================================
 * mbh2dmpmp_vec - multipole to multipole translation
 * (too complex for template - hand-translated from Fortran)
 * ================================================================ */
/* Stub: see gen script note. Full translation in separate file. */

void FNAME(mbh2dmpmp_vec)(
    const fint *nd_p, const double *beta_p,
    const double *rscale1_p, const double *center1,
    const fcomplex *mbhmpole1, const fcomplex *ympole1, const fint *nterms1_p,
    const double *rscale2_p, const double *center2,
    fcomplex *mbhmpole2, fcomplex *ympole2, const fint *nterms2_p)
{
    fint nd = *nd_p, nterms1 = *nterms1_p, nterms2 = *nterms2_p;
    double beta = *beta_p, rscale1 = *rscale1_p, rscale2 = *rscale2_p;
    fcomplex ima = I;
    double pi = 4.0 * atan(1.0);

    fint nterms = nterms1 + nterms2;
    fint alloc_sz = nterms + 7;
    fcomplex *jtemp = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *difftemp = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *powtemp = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    double *diffs = (double *)malloc(alloc_sz * sizeof(double));
    double *ival = (double *)malloc(alloc_sz * sizeof(double));
    double *pow_arr = (double *)malloc(alloc_sz * sizeof(double));
    double *dpow = (double *)malloc(alloc_sz * sizeof(double));

    double zdiff[2];
    zdiff[0] = center2[0] - center1[0];
    zdiff[1] = center2[1] - center1[1];
    double r, theta;
    h2cart2polar_(zdiff, &r, &theta);
    theta = theta - pi;

    fint ifder = 0;
    double ders_loc[2];
    diffszkik_fast_(&r, &beta, &rscale1, diffs, &ifder, ders_loc, ival, &nterms);

    FNAME(mbh2d_rksc)(pow_arr, dpow, &r, &beta, &rscale1, &nterms);

    jtemp[0] = ival[0];
    difftemp[0] = diffs[0];
    powtemp[0] = pow_arr[0];
    fcomplex zmul = cexp(ima * theta);
    fcomplex ztemp1 = zmul;
    for (fint j = 1; j <= nterms; j++) {
        jtemp[j] = ztemp1 * ival[j];
        difftemp[j] = ztemp1 * diffs[j];
        powtemp[j] = ztemp1 * pow_arr[j];
        ztemp1 = ztemp1 * zmul;
    }

    /* shift the expansion */
    double rsj = rscale1;

    for (fint l = 1; l <= nd; l++) {
        ympole2[l-1] += creal(ympole1[l-1]) * jtemp[0];
        ympole2[l-1] += creal(mbhmpole1[l-1]) * difftemp[0];
        mbhmpole2[l-1] += creal(mbhmpole1[l-1]);
    }

    for (fint j = 1; j <= nterms1; j++) {
        for (fint l = 1; l <= nd; l++) {
            ympole2[l-1] +=
                (creal(ympole1[j*nd+l-1]) * creal(jtemp[j])
                + cimag(ympole1[j*nd+l-1]) * cimag(jtemp[j])) * rsj * rsj;
            ympole2[l-1] +=
                (creal(mbhmpole1[j*nd+l-1]) * creal(jtemp[j])
                + cimag(mbhmpole1[j*nd+l-1]) * cimag(jtemp[j])) * rsj * rsj;
        }
        rsj *= rscale1;
    }

    double rsi = rscale1;
    double rsi5 = rscale1 / rscale2;
    for (fint i = 1; i <= nterms2; i++) {
        for (fint l = 1; l <= nd; l++) {
            ympole2[i*nd+l-1] +=
                2.0 * (creal(ympole1[l-1]) * creal(jtemp[i])
                + ima * creal(ympole1[l-1]) * cimag(jtemp[i])) * rsi5;
            ympole2[i*nd+l-1] +=
                2.0 * (creal(mbhmpole1[l-1]) * creal(difftemp[i])
                + ima * creal(mbhmpole1[l-1]) * cimag(difftemp[i])) * rsi5;
            mbhmpole2[i*nd+l-1] +=
                2.0 * (creal(mbhmpole1[l-1]) * creal(powtemp[i])
                + ima * creal(mbhmpole1[l-1]) * cimag(powtemp[i])) * rsi5;
        }
        rsj = rscale1;
        for (fint j = 1; j <= (nterms1 < i ? nterms1 : i); j++) {
            for (fint l = 1; l <= nd; l++) {
                ympole2[i*nd+l-1] +=
                    (creal(ympole1[j*nd+l-1]) * creal(jtemp[i-j])
                    - cimag(ympole1[j*nd+l-1]) * cimag(jtemp[i-j])
                    + ima * (creal(ympole1[j*nd+l-1]) * cimag(jtemp[i-j])
                    + cimag(ympole1[j*nd+l-1]) * creal(jtemp[i-j]))) * rsi5;
                ympole2[i*nd+l-1] +=
                    (creal(ympole1[j*nd+l-1]) * creal(jtemp[i+j])
                    + cimag(ympole1[j*nd+l-1]) * cimag(jtemp[i+j])
                    + ima * (creal(ympole1[j*nd+l-1]) * cimag(jtemp[i+j])
                    - cimag(ympole1[j*nd+l-1]) * creal(jtemp[i+j]))) * rsj * rsj * rsi5;
                mbhmpole2[i*nd+l-1] +=
                    (creal(mbhmpole1[j*nd+l-1]) * creal(powtemp[i-j])
                    - cimag(mbhmpole1[j*nd+l-1]) * cimag(powtemp[i-j])
                    + ima * (creal(mbhmpole1[j*nd+l-1]) * cimag(powtemp[i-j])
                    + cimag(mbhmpole1[j*nd+l-1]) * creal(powtemp[i-j]))) * rsi5;
                fcomplex ztemp = difftemp[i-j];
                ympole2[i*nd+l-1] +=
                    (creal(mbhmpole1[j*nd+l-1]) * creal(ztemp)
                    - cimag(mbhmpole1[j*nd+l-1]) * cimag(ztemp)
                    + ima * (creal(mbhmpole1[j*nd+l-1]) * cimag(ztemp)
                    + cimag(mbhmpole1[j*nd+l-1]) * creal(ztemp))) * rsi5;
                ympole2[i*nd+l-1] +=
                    (creal(mbhmpole1[j*nd+l-1]) * creal(jtemp[i+j])
                    + cimag(mbhmpole1[j*nd+l-1]) * cimag(jtemp[i+j])
                    + ima * (creal(mbhmpole1[j*nd+l-1]) * cimag(jtemp[i+j])
                    - cimag(mbhmpole1[j*nd+l-1]) * creal(jtemp[i+j]))) * rsj * rsj * rsi5;
            }
            rsj *= rscale1;
        }
        rsj = pow(rscale1, i + 1);
        double fs2 = rsi5 * rscale1 * rscale1;
        for (fint j = i + 1; j <= nterms1; j++) {
            for (fint l = 1; l <= nd; l++) {
                ympole2[i*nd+l-1] +=
                    (creal(mbhmpole1[j*nd+l-1]) * creal(jtemp[j-i])
                    + cimag(mbhmpole1[j*nd+l-1]) * cimag(jtemp[j-i])
                    - ima * (creal(mbhmpole1[j*nd+l-1]) * cimag(jtemp[j-i])
                    - cimag(mbhmpole1[j*nd+l-1]) * creal(jtemp[j-i]))) * fs2;
                ympole2[i*nd+l-1] +=
                    (creal(mbhmpole1[j*nd+l-1]) * creal(jtemp[i+j])
                    + cimag(mbhmpole1[j*nd+l-1]) * cimag(jtemp[i+j])
                    + ima * (creal(mbhmpole1[j*nd+l-1]) * cimag(jtemp[i+j])
                    - cimag(mbhmpole1[j*nd+l-1]) * creal(jtemp[i+j]))) * rsj * rsj * rsi5;
                ympole2[i*nd+l-1] +=
                    (creal(ympole1[j*nd+l-1]) * creal(jtemp[j-i])
                    + cimag(ympole1[j*nd+l-1]) * cimag(jtemp[j-i])
                    - ima * (creal(ympole1[j*nd+l-1]) * cimag(jtemp[j-i])
                    - cimag(ympole1[j*nd+l-1]) * creal(jtemp[j-i]))) * fs2;
                ympole2[i*nd+l-1] +=
                    (creal(ympole1[j*nd+l-1]) * creal(jtemp[i+j])
                    + cimag(ympole1[j*nd+l-1]) * cimag(jtemp[i+j])
                    + ima * (creal(ympole1[j*nd+l-1]) * cimag(jtemp[i+j])
                    - cimag(ympole1[j*nd+l-1]) * creal(jtemp[i+j]))) * rsj * rsj * rsi5;
            }
            rsj *= rscale1;
            fs2 *= rscale1 * rscale1;
        }
        rsi *= rscale1;
        rsi5 *= rscale1 / rscale2;
    }

    free(jtemp); free(difftemp); free(powtemp);
    free(diffs); free(ival); free(pow_arr); free(dpow);
}

/* ================================================================
 * mbh2dmploc_vec - multipole to local translation
 * ================================================================ */

void FNAME(mbh2dmploc_vec)(
    const fint *nd_p, const double *beta_p,
    const double *rscale1_p, const double *center1,
    const fcomplex *mbhmpole, const fcomplex *ympole, const fint *nterms1_p,
    const double *rscale2_p, const double *center2,
    fcomplex *mbhloc, fcomplex *lloc, const fint *nterms2_p)
{
    fint nd = *nd_p, nterms1 = *nterms1_p, nterms2 = *nterms2_p;
    double beta = *beta_p, rscale1 = *rscale1_p, rscale2 = *rscale2_p;
    fcomplex ima = I;
    double pi = 4.0 * atan(1.0);

    fint nterms = nterms1 + nterms2;
    fint alloc_sz = nterms + 7;
    double *diffs = (double *)malloc(alloc_sz * sizeof(double));
    double *kvec = (double *)malloc(alloc_sz * sizeof(double));
    double *pow_arr = (double *)malloc(alloc_sz * sizeof(double));
    double *dpow_arr = (double *)malloc(alloc_sz * sizeof(double));
    double *dfac2 = (double *)malloc(alloc_sz * sizeof(double));
    fcomplex *ktemp = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *difftemp = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *powtemp = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));

    dfac2[0] = 1.0;
    for (fint i = 1; i <= nterms; i++) {
        dfac2[i] = dfac2[i-1] / (2.0 * i);
    }

    double zdiff[2];
    zdiff[0] = center2[0] - center1[0];
    zdiff[1] = center2[1] - center1[1];
    double r, theta;
    h2cart2polar_(zdiff, &r, &theta);
    theta = theta - pi;

    /* get values of (beta*r)^-k */
    FNAME(mbh2d_rmk)(pow_arr, dpow_arr, &r, &beta, &rscale1, &nterms);

    /* get values of difference functions */
    fint ifders = 0;
    double ders_loc[2];
    diffslogbk_fast_(&r, &beta, &rscale1, diffs, &ifders, ders_loc, kvec,
        &nterms);

    /* form terms for shifting */
    ktemp[0] = kvec[0];
    difftemp[0] = diffs[0];
    powtemp[0] = pow_arr[0];
    fcomplex zmul = -cexp(ima * theta);
    fcomplex ztemp1 = zmul;
    for (fint j = 1; j <= nterms; j++) {
        ktemp[j] = ztemp1 * kvec[j];
        difftemp[j] = ztemp1 * diffs[j];
        powtemp[j] = ztemp1 * pow_arr[j];
        ztemp1 = ztemp1 * zmul;
    }

    /* shift - i=0 terms */
    for (fint l = 1; l <= nd; l++) {
        mbhloc[l-1] += mbhmpole[l-1] * ktemp[0];
        mbhloc[l-1] += ympole[l-1] * ktemp[0];
        lloc[l-1] += mbhmpole[l-1] * (ktemp[0] + pow_arr[0]);
        lloc[l-1] += ympole[l-1] * ktemp[0];
    }
    for (fint j = 1; j <= nterms1; j++) {
        for (fint l = 1; l <= nd; l++) {
            mbhloc[l-1] +=
                (creal(mbhmpole[j*nd+l-1]) * creal(ktemp[j])
                + cimag(mbhmpole[j*nd+l-1]) * cimag(ktemp[j]));
            mbhloc[l-1] +=
                (creal(ympole[j*nd+l-1]) * creal(ktemp[j])
                + cimag(ympole[j*nd+l-1]) * cimag(ktemp[j]));
            lloc[l-1] +=
                (creal(mbhmpole[j*nd+l-1]) * creal(difftemp[j])
                + cimag(mbhmpole[j*nd+l-1]) * cimag(difftemp[j]));
            lloc[l-1] +=
                (creal(ympole[j*nd+l-1]) * creal(ktemp[j])
                + cimag(ympole[j*nd+l-1]) * cimag(ktemp[j]));
        }
    }

    /* shift - i >= 1 terms */
    double rsi = rscale1;
    double rsi2 = rscale1 * rscale1;
    double rsi5 = rscale2 / rscale1;
    fint isign = -1;
    for (fint i = 1; i <= nterms2; i++) {
        double dtmp1 = isign * rsi5 * 2;
        double dtmp2 = dtmp1 * dfac2[i];
        for (fint l = 1; l <= nd; l++) {
            mbhloc[i*nd+l-1] += dtmp1 *
                creal(mbhmpole[l-1]) * ktemp[i];
            mbhloc[i*nd+l-1] += dtmp1 *
                creal(ympole[l-1]) * ktemp[i];
            lloc[i*nd+l-1] += dtmp2 *
                creal(mbhmpole[l-1]) * difftemp[i];
            lloc[i*nd+l-1] += dtmp2 *
                creal(ympole[l-1]) * ktemp[i];
        }
        double rsj = rscale1;
        double rsj2 = rscale1 * rscale1;
        dtmp1 = isign * rsi5;
        dtmp2 = dtmp1 * dfac2[i];
        for (fint j = 1; j <= (nterms1 < i ? nterms1 : i); j++) {
            double dtmp3 = dtmp1 * rsj2;
            double dtmp4 = dtmp2 * rsj2;

            for (fint l = 1; l <= nd; l++) {
                mbhloc[i*nd+l-1] += dtmp3 *
                    (mbhmpole[j*nd+l-1] + ympole[j*nd+l-1]) * ktemp[i-j];
                mbhloc[i*nd+l-1] += dtmp1 *
                    conj(mbhmpole[j*nd+l-1] + ympole[j*nd+l-1]) * ktemp[i+j];
                lloc[i*nd+l-1] += dtmp4 *
                    (mbhmpole[j*nd+l-1] + ympole[j*nd+l-1]) * ktemp[i-j];
                lloc[i*nd+l-1] += dtmp2 *
                    conj(mbhmpole[j*nd+l-1]) * difftemp[i+j];
                lloc[i*nd+l-1] += dtmp2 *
                    conj(ympole[j*nd+l-1]) * ktemp[i+j];
            }
            rsj = rsj * rscale1;
            rsj2 = rsj2 * rscale1 * rscale1;
        }
        double dtmp3 = dtmp1 * rsi2;
        double dtmp4 = dtmp2 * rsi2;
        for (fint j = i + 1; j <= nterms1; j++) {
            for (fint l = 1; l <= nd; l++) {
                mbhloc[i*nd+l-1] += dtmp3 *
                    (mbhmpole[j*nd+l-1] + ympole[j*nd+l-1]) * conj(ktemp[j-i]);
                mbhloc[i*nd+l-1] += dtmp1 *
                    conj(mbhmpole[j*nd+l-1] + ympole[j*nd+l-1]) * ktemp[i+j];
                lloc[i*nd+l-1] += dtmp4 *
                    (mbhmpole[j*nd+l-1] + ympole[j*nd+l-1]) * conj(ktemp[j-i]);
                lloc[i*nd+l-1] += dtmp2 *
                    conj(mbhmpole[j*nd+l-1]) * difftemp[i+j];
                lloc[i*nd+l-1] += dtmp2 *
                    conj(ympole[j*nd+l-1]) * ktemp[i+j];
            }
        }
        isign = -isign;
        rsi = rsi * rscale1;
        rsi2 = rsi2 * rscale1 * rscale1;
        rsi5 = rsi5 * rscale2 / rscale1;
    }

    free(ktemp); free(difftemp); free(powtemp);
    free(diffs); free(kvec); free(pow_arr); free(dpow_arr); free(dfac2);
}

/* ================================================================
 * mbh2dlocloc_vec - local to local translation
 * ================================================================ */

void FNAME(mbh2dlocloc_vec)(
    const fint *nd_p, const double *beta_p,
    const double *rscale1_p, const double *center1,
    const fcomplex *mbhloc1, const fcomplex *lloc1, const fint *nterms1_p,
    const double *rscale2_p, const double *center2,
    fcomplex *mbhloc2, fcomplex *lloc2, const fint *nterms2_p,
    const double *carray, const fint *ldc_p)
{
    fint nd = *nd_p, nterms1 = *nterms1_p, nterms2 = *nterms2_p;
    double beta = *beta_p, rscale1 = *rscale1_p, rscale2 = *rscale2_p;
    fint ldc = *ldc_p;
    fcomplex ima = I;
    double pi = 4.0 * atan(1.0);

    fint nterms = nterms1 + nterms2;
    fint alloc_sz = nterms + 7;
    fcomplex *jtemp = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *difftemp = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *powtemp = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    double *ival = (double *)malloc(alloc_sz * sizeof(double));
    double *diffs = (double *)malloc(alloc_sz * sizeof(double));
    double *pow_arr = (double *)malloc(alloc_sz * sizeof(double));
    double *dpow_arr = (double *)malloc(alloc_sz * sizeof(double));
    double *pow2 = (double *)malloc(alloc_sz * sizeof(double));
    double *dfac2 = (double *)malloc(alloc_sz * sizeof(double));

    double zdiff[2];
    zdiff[0] = center2[0] - center1[0];
    zdiff[1] = center2[1] - center1[1];
    double r, theta;
    h2cart2polar_(zdiff, &r, &theta);
    theta = theta - pi;

    fint ifder = 0;
    double ders_loc[2];
    diffszkik_fast_(&r, &beta, &rscale1, diffs, &ifder, ders_loc, ival,
        &nterms);

    FNAME(mbh2d_rk)(pow_arr, dpow_arr, &r, &beta, &rscale1, &nterms);
    FNAME(mbh2d_rksc)(pow2, dpow_arr, &r, &beta, &rscale1, &nterms);

    dfac2[0] = 1.0;
    for (fint i = 1; i <= nterms; i++) {
        dfac2[i] = dfac2[i-1] / (2.0 * i);
    }

    jtemp[0] = ival[0];
    powtemp[0] = pow_arr[0];
    difftemp[0] = diffs[0];
    fcomplex zmul = -cexp(ima * theta);
    fcomplex ztemp1 = zmul;
    for (fint j = 1; j <= nterms; j++) {
        jtemp[j] = ztemp1 * ival[j];
        difftemp[j] = ztemp1 * diffs[j];
        powtemp[j] = ztemp1 * pow_arr[j];
        ztemp1 = ztemp1 * zmul;
    }

    /* i=0 terms */
    for (fint l = 1; l <= nd; l++) {
        mbhloc2[l-1] += mbhloc1[l-1] * jtemp[0];
        lloc2[l-1] += mbhloc1[l-1] * difftemp[0];
        lloc2[l-1] += lloc1[l-1] * powtemp[0];
    }
    for (fint j = 1; j <= nterms1; j++) {
        for (fint l = 1; l <= nd; l++) {
            mbhloc2[l-1] +=
                (creal(mbhloc1[j*nd+l-1]) * creal(jtemp[j])
                + cimag(mbhloc1[j*nd+l-1]) * cimag(jtemp[j]));
            lloc2[l-1] +=
                (creal(mbhloc1[j*nd+l-1]) * creal(difftemp[j])
                + cimag(mbhloc1[j*nd+l-1]) * cimag(difftemp[j]));
            lloc2[l-1] +=
                (creal(lloc1[j*nd+l-1]) * creal(powtemp[j])
                + cimag(lloc1[j*nd+l-1]) * cimag(powtemp[j]));
        }
    }

    /* i >= 1 terms */
    double rsi = rscale1;
    double rsi7 = rscale2;
    double rsi5 = rscale2 / rscale1;
    for (fint i = 1; i <= nterms2; i++) {
        for (fint l = 1; l <= nd; l++) {
            mbhloc2[i*nd+l-1] +=
                2.0 * (creal(mbhloc1[l-1]) * creal(jtemp[i])
                + ima * creal(mbhloc1[l-1]) * cimag(jtemp[i])) * rsi7 * rsi;
            lloc2[i*nd+l-1] +=
                2.0 * (creal(mbhloc1[l-1]) * creal(jtemp[i])
                + ima * creal(mbhloc1[l-1]) * cimag(jtemp[i])) * rsi7 * rsi *
                dfac2[i];
        }
        double fs2 = rsi5 * rscale1 * rscale1;
        if (nterms1 <= i - 1)
            fs2 = fs2 * pow(rscale1, 2 * (i - 1 - nterms1));
        for (fint j = (nterms1 < i - 1 ? nterms1 : i - 1); j >= 1; j--) {
            for (fint l = 1; l <= nd; l++) {
                mbhloc2[i*nd+l-1] +=
                    (creal(mbhloc1[j*nd+l-1]) * creal(jtemp[i-j])
                    - cimag(mbhloc1[j*nd+l-1]) * cimag(jtemp[i-j])
                    + ima * (creal(mbhloc1[j*nd+l-1]) * cimag(jtemp[i-j])
                    + cimag(mbhloc1[j*nd+l-1]) * creal(jtemp[i-j]))) * fs2;
                mbhloc2[i*nd+l-1] +=
                    (creal(mbhloc1[j*nd+l-1]) * creal(jtemp[i+j])
                    + cimag(mbhloc1[j*nd+l-1]) * cimag(jtemp[i+j])
                    + ima * (creal(mbhloc1[j*nd+l-1]) * cimag(jtemp[i+j])
                    - cimag(mbhloc1[j*nd+l-1]) * creal(jtemp[i+j]))) * rsi * rsi7;
                lloc2[i*nd+l-1] +=
                    (creal(mbhloc1[j*nd+l-1]) * creal(jtemp[i-j])
                    - cimag(mbhloc1[j*nd+l-1]) * cimag(jtemp[i-j])
                    + ima * (creal(mbhloc1[j*nd+l-1]) * cimag(jtemp[i-j])
                    + cimag(mbhloc1[j*nd+l-1]) * creal(jtemp[i-j]))) * fs2 *
                    dfac2[i];
                lloc2[i*nd+l-1] +=
                    (creal(mbhloc1[j*nd+l-1]) * creal(jtemp[i+j])
                    + cimag(mbhloc1[j*nd+l-1]) * cimag(jtemp[i+j])
                    + ima * (creal(mbhloc1[j*nd+l-1]) * cimag(jtemp[i+j])
                    - cimag(mbhloc1[j*nd+l-1]) * creal(jtemp[i+j])))
                    * rsi * rsi7 * dfac2[i];
            }
            fs2 = fs2 * rscale1 * rscale1;
        }
        for (fint j = i; j <= nterms1; j++) {
            for (fint l = 1; l <= nd; l++) {
                mbhloc2[i*nd+l-1] +=
                    (creal(mbhloc1[j*nd+l-1]) * creal(jtemp[j-i])
                    + cimag(mbhloc1[j*nd+l-1]) * cimag(jtemp[j-i])
                    - ima * (creal(mbhloc1[j*nd+l-1]) * cimag(jtemp[j-i])
                    - cimag(mbhloc1[j*nd+l-1]) * creal(jtemp[j-i]))) * rsi5;
                lloc2[i*nd+l-1] +=
                    (creal(mbhloc1[j*nd+l-1]) * creal(difftemp[j-i])
                    + cimag(mbhloc1[j*nd+l-1]) * cimag(difftemp[j-i])
                    - ima * (creal(mbhloc1[j*nd+l-1]) * cimag(difftemp[j-i])
                    - cimag(mbhloc1[j*nd+l-1]) * creal(difftemp[j-i]))) * rsi5
                    * dfac2[i];
                lloc2[i*nd+l-1] +=
                    (creal(lloc1[j*nd+l-1]) * creal(powtemp[j-i])
                    + cimag(lloc1[j*nd+l-1]) * cimag(powtemp[j-i])
                    - ima * (creal(lloc1[j*nd+l-1]) * cimag(powtemp[j-i])
                    - cimag(lloc1[j*nd+l-1]) * creal(powtemp[j-i])))
                    * carray[i * (ldc + 1) + j] * rsi5;
                mbhloc2[i*nd+l-1] +=
                    (creal(mbhloc1[j*nd+l-1]) * creal(jtemp[i+j])
                    + cimag(mbhloc1[j*nd+l-1]) * cimag(jtemp[i+j])
                    + ima * (creal(mbhloc1[j*nd+l-1]) * cimag(jtemp[i+j])
                    - cimag(mbhloc1[j*nd+l-1]) * creal(jtemp[i+j]))) * rsi * rsi7;
                lloc2[i*nd+l-1] +=
                    (creal(mbhloc1[j*nd+l-1]) * creal(jtemp[i+j])
                    + cimag(mbhloc1[j*nd+l-1]) * cimag(jtemp[i+j])
                    + ima * (creal(mbhloc1[j*nd+l-1]) * cimag(jtemp[i+j])
                    - cimag(mbhloc1[j*nd+l-1]) * creal(jtemp[i+j])))
                    * rsi * rsi7 * dfac2[i];
            }
        }
        rsi = rsi * rscale1;
        rsi7 = rsi7 * rscale2;
        rsi5 = rsi5 * rscale2 / rscale1;
    }

    free(jtemp); free(difftemp); free(powtemp);
    free(diffs); free(ival); free(pow_arr); free(dpow_arr);
    free(pow2); free(dfac2);
}
