#!/usr/bin/env python3
"""
Generate mbhkernels2d.c from the same kernel/output combinations
as the Fortran jinja template (mbhkernels2d.f.j2).

Usage: python3 gen_mbhkernels2d.py > src/mbhkernels2d.c
"""

import sys

# Same routing list as jinjaroot.yaml
KERS = ["c","d","cd","q","cq","dq","cdq",
        "o","co","do","cdo","qo","cqo","dqo","cdqo"]
OUTS = ["p","g","h"]

direct_routs = []
for out in OUTS:
    for ker in KERS:
        name = f"mbh2d_direct{ker}{out}_vec"
        direct_routs.append({"name": name, "ker": ker, "out": out})

eval_routs = [{"out": o} for o in OUTS]

def emit_header():
    print("""/*
 * mbhkernels2d.c
 *
 * C translation of src/modified-biharmonic/mbhkernels2d.f
 * (auto-generated by gen_mbhkernels2d.py)
 *
 * 45 direct kernel evaluation routines + 3 multipolar source routines.
 */

#include "fmm2d_c.h"
#include "mbhkernels2d.h"
#include "mbhgreen2d.h"

/* Cross-file calls */
extern void modbhgreen_all_(const double *beta, const double *zx,
    const double *zy, const fint *ifpot, double *pot,
    const fint *ifgrad, double *grad, const fint *ifhess, double *hess,
    const fint *ifder3, double *der3, const fint *ifder4, double *der4,
    const fint *ifder5, double *der5);
extern void h2cart2polar_(const double *zat, double *r, double *theta);
extern void diffslogbk_fast_(const double *x, const double *beta,
    const double *rscale, double *diffs, const fint *ifders,
    double *ders, double *kvec, const fint *n);
""")

def params_for(ker, out):
    """Return parameter list for a direct routine."""
    args = ["const fint *nd_p", "const double *beta_p",
            "const double *source", "const fint *ns_p"]
    if "c" in ker:
        args.append("const double *charge")
    if "d" in ker:
        args += ["const double *dipstr", "const double *dipvec"]
    if "q" in ker:
        args += ["const double *quadstr", "const double *quadvec"]
    if "o" in ker:
        args += ["const double *octstr", "const double *octvec"]
    args += ["const double *targ", "const fint *nt_p"]
    if out in ("p","g","h"):
        args.append("double *pot")
    if out in ("g","h"):
        args.append("double *grad")
    if out == "h":
        args.append("double *hess")
    args.append("const double *thresh_p")
    return args

def emit_direct_routine(rout):
    name = rout["name"]
    ker = rout["ker"]
    out = rout["out"]

    args = params_for(ker, out)
    sig = f"void FNAME({name})(\n    " + ",\n    ".join(args) + ")"

    # Which derivative levels does modbhgreen_all need?
    need_grad = True   # always needed for dipole contrib; charge only needs potloc
    need_hess = True   # needed for dipole grad, charge hess, quad pot
    need_der3 = ("d" in ker and out in ("h",)) or ("q" in ker and out in ("g","h")) or ("o" in ker)
    need_der4 = ("q" in ker and out == "h") or ("o" in ker and out in ("g","h"))
    need_der5 = ("o" in ker and out == "h")

    # Actually in the Fortran template, ifpotloc through ifder5 are ALL set to 1 unconditionally.
    # This simplifies things. Let me re-read...
    # Yes: "ifpotloc=1, ifgradloc=1, ifhessloc=1, ifder3=1, ifder4=1, ifder5=1"
    # They're all set to 1 for all routines. The actual outputs just selectively use them.

    print(f"\n{sig}")
    print("{")
    print("    fint nd_v = *nd_p, ns_v = *ns_p, nt_v = *nt_p;")
    print("    double thresh2 = (*thresh_p) * (*thresh_p);")
    print("")
    print("    fint ifpotloc = 1, ifgradloc = 1, ifhessloc = 1;")
    print("    fint ifder3 = 1, ifder4 = 1, ifder5 = 1;")
    print("")
    print("    for (fint i = 1; i <= ns_v; i++) {")
    print("        for (fint j = 1; j <= nt_v; j++) {")
    print("            double xdiff = targ[FA2(1,j,2)] - source[FA2(1,i,2)];")
    print("            double ydiff = targ[FA2(2,j,2)] - source[FA2(2,i,2)];")
    print("            double rr = xdiff * xdiff + ydiff * ydiff;")
    print("            if (rr < thresh2) continue;")
    print("")
    print("            double potloc, gradloc[2], hessloc[3];")
    print("            double der3loc[4], der4loc[5], der5loc[6];")
    print("            const double targ_j[2] = {targ[FA2(1,j,2)], targ[FA2(2,j,2)]};")
    print("            const double src_i[2] = {source[FA2(1,i,2)], source[FA2(2,i,2)]};")
    # Calling modbhgreen_all: same-file? No, it's in mbhgreen2d.c.
    # Cross-file call, use bare Fortran name.
    print("            modbhgreen_all_(beta_p, targ_j, src_i,")
    print("                &ifpotloc, &potloc, &ifgradloc, gradloc,")
    print("                &ifhessloc, hessloc, &ifder3, der3loc,")
    print("                &ifder4, der4loc, &ifder5, der5loc);")
    print("")
    print("            for (fint ii = 1; ii <= nd_v; ii++) {")

    # charge contrib
    if "c" in ker:
        print("                /* charge contrib */")
        if out in ("p","g","h"):
            print("                pot[FA2(ii,j,nd_v)] += potloc * charge[FA2(ii,i,nd_v)];")
        if out in ("g","h"):
            print("                grad[FA3(ii,1,j,nd_v,2)] += gradloc[0] * charge[FA2(ii,i,nd_v)];")
            print("                grad[FA3(ii,2,j,nd_v,2)] += gradloc[1] * charge[FA2(ii,i,nd_v)];")
        if out == "h":
            print("                hess[FA3(ii,1,j,nd_v,3)] += hessloc[0] * charge[FA2(ii,i,nd_v)];")
            print("                hess[FA3(ii,2,j,nd_v,3)] += hessloc[1] * charge[FA2(ii,i,nd_v)];")
            print("                hess[FA3(ii,3,j,nd_v,3)] += hessloc[2] * charge[FA2(ii,i,nd_v)];")

    # dipole contrib
    if "d" in ker:
        print("                /* dipole contrib */")
        if out in ("p","g","h"):
            print("                pot[FA2(ii,j,nd_v)] -=")
            print("                    dipstr[FA2(ii,i,nd_v)] * (gradloc[0] * dipvec[FA3(ii,1,i,nd_v,2)]")
            print("                    + gradloc[1] * dipvec[FA3(ii,2,i,nd_v,2)]);")
        if out in ("g","h"):
            print("                grad[FA3(ii,1,j,nd_v,2)] -=")
            print("                    dipstr[FA2(ii,i,nd_v)] * (hessloc[0] * dipvec[FA3(ii,1,i,nd_v,2)]")
            print("                    + hessloc[1] * dipvec[FA3(ii,2,i,nd_v,2)]);")
            print("                grad[FA3(ii,2,j,nd_v,2)] -=")
            print("                    dipstr[FA2(ii,i,nd_v)] * (hessloc[1] * dipvec[FA3(ii,1,i,nd_v,2)]")
            print("                    + hessloc[2] * dipvec[FA3(ii,2,i,nd_v,2)]);")
        if out == "h":
            print("                hess[FA3(ii,1,j,nd_v,3)] -=")
            print("                    dipstr[FA2(ii,i,nd_v)] * (der3loc[0] * dipvec[FA3(ii,1,i,nd_v,2)]")
            print("                    + der3loc[1] * dipvec[FA3(ii,2,i,nd_v,2)]);")
            print("                hess[FA3(ii,2,j,nd_v,3)] -=")
            print("                    dipstr[FA2(ii,i,nd_v)] * (der3loc[1] * dipvec[FA3(ii,1,i,nd_v,2)]")
            print("                    + der3loc[2] * dipvec[FA3(ii,2,i,nd_v,2)]);")
            print("                hess[FA3(ii,3,j,nd_v,3)] -=")
            print("                    dipstr[FA2(ii,i,nd_v)] * (der3loc[2] * dipvec[FA3(ii,1,i,nd_v,2)]")
            print("                    + der3loc[3] * dipvec[FA3(ii,2,i,nd_v,2)]);")

    # quadrupole contrib
    if "q" in ker:
        print("                /* quadrupole contrib */")
        if out in ("p","g","h"):
            print("                pot[FA2(ii,j,nd_v)] +=")
            print("                    quadstr[FA2(ii,i,nd_v)] * (hessloc[0] * quadvec[FA3(ii,1,i,nd_v,3)]")
            print("                    + hessloc[1] * quadvec[FA3(ii,2,i,nd_v,3)]")
            print("                    + hessloc[2] * quadvec[FA3(ii,3,i,nd_v,3)]);")
        if out in ("g","h"):
            print("                grad[FA3(ii,1,j,nd_v,2)] +=")
            print("                    quadstr[FA2(ii,i,nd_v)] * (der3loc[0] * quadvec[FA3(ii,1,i,nd_v,3)]")
            print("                    + der3loc[1] * quadvec[FA3(ii,2,i,nd_v,3)]")
            print("                    + der3loc[2] * quadvec[FA3(ii,3,i,nd_v,3)]);")
            print("                grad[FA3(ii,2,j,nd_v,2)] +=")
            print("                    quadstr[FA2(ii,i,nd_v)] * (der3loc[1] * quadvec[FA3(ii,1,i,nd_v,3)]")
            print("                    + der3loc[2] * quadvec[FA3(ii,2,i,nd_v,3)]")
            print("                    + der3loc[3] * quadvec[FA3(ii,3,i,nd_v,3)]);")
        if out == "h":
            print("                hess[FA3(ii,1,j,nd_v,3)] +=")
            print("                    quadstr[FA2(ii,i,nd_v)] * (der4loc[0] * quadvec[FA3(ii,1,i,nd_v,3)]")
            print("                    + der4loc[1] * quadvec[FA3(ii,2,i,nd_v,3)]")
            print("                    + der4loc[2] * quadvec[FA3(ii,3,i,nd_v,3)]);")
            print("                hess[FA3(ii,2,j,nd_v,3)] +=")
            print("                    quadstr[FA2(ii,i,nd_v)] * (der4loc[1] * quadvec[FA3(ii,1,i,nd_v,3)]")
            print("                    + der4loc[2] * quadvec[FA3(ii,2,i,nd_v,3)]")
            print("                    + der4loc[3] * quadvec[FA3(ii,3,i,nd_v,3)]);")
            print("                hess[FA3(ii,3,j,nd_v,3)] +=")
            print("                    quadstr[FA2(ii,i,nd_v)] * (der4loc[2] * quadvec[FA3(ii,1,i,nd_v,3)]")
            print("                    + der4loc[3] * quadvec[FA3(ii,2,i,nd_v,3)]")
            print("                    + der4loc[4] * quadvec[FA3(ii,3,i,nd_v,3)]);")

    # octopole contrib
    if "o" in ker:
        print("                /* octopole contrib */")
        if out in ("p","g","h"):
            print("                pot[FA2(ii,j,nd_v)] -=")
            print("                    octstr[FA2(ii,i,nd_v)] * (der3loc[0] * octvec[FA3(ii,1,i,nd_v,4)]")
            print("                    + der3loc[1] * octvec[FA3(ii,2,i,nd_v,4)]")
            print("                    + der3loc[2] * octvec[FA3(ii,3,i,nd_v,4)]")
            print("                    + der3loc[3] * octvec[FA3(ii,4,i,nd_v,4)]);")
        if out in ("g","h"):
            print("                grad[FA3(ii,1,j,nd_v,2)] -=")
            print("                    octstr[FA2(ii,i,nd_v)] * (der4loc[0] * octvec[FA3(ii,1,i,nd_v,4)]")
            print("                    + der4loc[1] * octvec[FA3(ii,2,i,nd_v,4)]")
            print("                    + der4loc[2] * octvec[FA3(ii,3,i,nd_v,4)]")
            print("                    + der4loc[3] * octvec[FA3(ii,4,i,nd_v,4)]);")
            print("                grad[FA3(ii,2,j,nd_v,2)] -=")
            print("                    octstr[FA2(ii,i,nd_v)] * (der4loc[1] * octvec[FA3(ii,1,i,nd_v,4)]")
            print("                    + der4loc[2] * octvec[FA3(ii,2,i,nd_v,4)]")
            print("                    + der4loc[3] * octvec[FA3(ii,3,i,nd_v,4)]")
            print("                    + der4loc[4] * octvec[FA3(ii,4,i,nd_v,4)]);")
        if out == "h":
            print("                hess[FA3(ii,1,j,nd_v,3)] -=")
            print("                    octstr[FA2(ii,i,nd_v)] * (der5loc[0] * octvec[FA3(ii,1,i,nd_v,4)]")
            print("                    + der5loc[1] * octvec[FA3(ii,2,i,nd_v,4)]")
            print("                    + der5loc[2] * octvec[FA3(ii,3,i,nd_v,4)]")
            print("                    + der5loc[3] * octvec[FA3(ii,4,i,nd_v,4)]);")
            print("                hess[FA3(ii,2,j,nd_v,3)] -=")
            print("                    octstr[FA2(ii,i,nd_v)] * (der5loc[1] * octvec[FA3(ii,1,i,nd_v,4)]")
            print("                    + der5loc[2] * octvec[FA3(ii,2,i,nd_v,4)]")
            print("                    + der5loc[3] * octvec[FA3(ii,3,i,nd_v,4)]")
            print("                    + der5loc[4] * octvec[FA3(ii,4,i,nd_v,4)]);")
            print("                hess[FA3(ii,3,j,nd_v,3)] -=")
            print("                    octstr[FA2(ii,i,nd_v)] * (der5loc[2] * octvec[FA3(ii,1,i,nd_v,4)]")
            print("                    + der5loc[3] * octvec[FA3(ii,2,i,nd_v,4)]")
            print("                    + der5loc[4] * octvec[FA3(ii,3,i,nd_v,4)]")
            print("                    + der5loc[5] * octvec[FA3(ii,4,i,nd_v,4)]);")

    print("            } /* ii */")
    print("        } /* j */")
    print("    } /* i */")
    print("}")


def emit_mps_p():
    """Emit mbh2d_directmpsp_vec."""
    print("""
void FNAME(mbh2d_directmpsp_vec)(
    const fint *nd_p, const double *beta_p, const double *source, const fint *ns_p,
    const fcomplex *mbhmps, const fcomplex *ymps, const fint *ntermsmps_p,
    const double *targ, const fint *nt_p, double *pot, const double *thresh_p)
{
    fint nd_v = *nd_p, ns_v = *ns_p, nt_v = *nt_p;
    fint ntermsmps = *ntermsmps_p;
    double beta = *beta_p, thresh = *thresh_p;
    double rscale = 1.0;
    fint nterms = ntermsmps;
    fcomplex eye = I;

    fint alloc_sz = nterms + 7;
    fcomplex *mptemp1 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *mptemp2 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    double *diffs = (double *)malloc(alloc_sz * sizeof(double));
    double *kvec = (double *)malloc(alloc_sz * sizeof(double));

    for (fint jj = 1; jj <= ns_v; jj++) {
        for (fint i = 1; i <= nt_v; i++) {
            double zdiff[2];
            zdiff[0] = targ[FA2(1,i,2)] - source[FA2(1,jj,2)];
            zdiff[1] = targ[FA2(2,i,2)] - source[FA2(2,jj,2)];
            double r, theta;
            h2cart2polar_(zdiff, &r, &theta);

            if (r < thresh) continue;

            fint ifders = 0;
            double ders_loc[2];
            fint nt2 = nterms + 2;
            diffslogbk_fast_(&r, &beta, &rscale, diffs, &ifders,
                             ders_loc, kvec, &nt2);

            mptemp1[0] = diffs[0];
            mptemp2[0] = kvec[0];
            fcomplex ztemp2 = cexp(eye * theta);
            fcomplex ztemp1 = ztemp2;
            for (fint j = 1; j <= nterms + 2; j++) {
                mptemp1[j] = diffs[j] * creal(ztemp1) + diffs[j] * cimag(ztemp1) * I;
                mptemp2[j] = kvec[j] * creal(ztemp1) + kvec[j] * cimag(ztemp1) * I;
                ztemp1 = ztemp1 * ztemp2;
            }

            /* pot accumulation - split multi-term additions */
            fint nt1_v = ntermsmps + 1; /* leading dim of mbhmps/ymps: 0:ntermsmps -> ntermsmps+1 */
            for (fint j = 1; j <= nd_v; j++) {
                pot[FA2(j,i,nd_v)] += creal(mptemp1[0]) * creal(mbhmps[FA3(j,0+1,jj,nd_v,nt1_v)]);
                pot[FA2(j,i,nd_v)] += creal(mptemp2[0]) * creal(ymps[FA3(j,0+1,jj,nd_v,nt1_v)]);
            }

            for (fint l = 1; l <= nterms; l++) {
                for (fint j = 1; j <= nd_v; j++) {
                    pot[FA2(j,i,nd_v)] += creal(mptemp1[l]) * creal(mbhmps[FA3(j,l+1,jj,nd_v,nt1_v)]);
                    pot[FA2(j,i,nd_v)] += cimag(mptemp1[l]) * cimag(mbhmps[FA3(j,l+1,jj,nd_v,nt1_v)]);
                    pot[FA2(j,i,nd_v)] += creal(mptemp2[l]) * creal(ymps[FA3(j,l+1,jj,nd_v,nt1_v)]);
                    pot[FA2(j,i,nd_v)] += cimag(mptemp2[l]) * cimag(ymps[FA3(j,l+1,jj,nd_v,nt1_v)]);
                }
            }
        }
    }
    free(mptemp1); free(mptemp2); free(diffs); free(kvec);
}""")


def emit_mps_g():
    """Emit mbh2d_directmpsg_vec - reads from generated Fortran."""
    # This is long; I'll emit it as a large string with the logic translated
    print("""
void FNAME(mbh2d_directmpsg_vec)(
    const fint *nd_p, const double *beta_p, const double *source, const fint *ns_p,
    const fcomplex *mbhmps, const fcomplex *ymps, const fint *ntermsmps_p,
    const double *targ, const fint *nt_p, double *pot, double *grad,
    const double *thresh_p)
{
    fint nd_v = *nd_p, ns_v = *ns_p, nt_v = *nt_p;
    fint ntermsmps = *ntermsmps_p;
    double beta = *beta_p, thresh = *thresh_p;
    double rscale = 1.0;
    fint nterms = ntermsmps;
    fcomplex eye = I;
    fint nt1_v = ntermsmps + 1;

    fint nt2 = nterms + 2;
    fint alloc_sz = nterms + 7;
    fcomplex *mptemp1 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *mptemp2 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    double *diffs = (double *)malloc(alloc_sz * sizeof(double));
    double *kvec = (double *)malloc(alloc_sz * sizeof(double));

    /* gradient derivative expansions: nd_v x (0:nterms+1) */
    fint gd = nterms + 2;
    fcomplex *ympolex   = (fcomplex *)calloc(nd_v * gd, sizeof(fcomplex));
    fcomplex *ympoley   = (fcomplex *)calloc(nd_v * gd, sizeof(fcomplex));
    fcomplex *mbhmpolex = (fcomplex *)calloc(nd_v * gd, sizeof(fcomplex));
    fcomplex *mbhmpoley = (fcomplex *)calloc(nd_v * gd, sizeof(fcomplex));

    for (fint jj = 1; jj <= ns_v; jj++) {

        /* zero derivative expansions */
        for (fint ii = 0; ii < nd_v * gd; ii++) {
            ympolex[ii] = 0; ympoley[ii] = 0;
            mbhmpolex[ii] = 0; mbhmpoley[ii] = 0;
        }

        /* index helper: (j, i) in nd_v x gd array, i is 0-based mode */
#define GI(j, imode) ((imode) * nd_v + ((j) - 1))

        for (fint j = 1; j <= nd_v; j++) {
            ympolex[GI(j,1)] = -beta / rscale * ymps[FA3(j,0+1,jj,nd_v,nt1_v)];
            ympoley[GI(j,1)] = -beta / rscale * ymps[FA3(j,0+1,jj,nd_v,nt1_v)] * eye;
            mbhmpolex[GI(j,1)] = -beta / rscale * mbhmps[FA3(j,0+1,jj,nd_v,nt1_v)];
            mbhmpoley[GI(j,1)] = -beta / rscale * mbhmps[FA3(j,0+1,jj,nd_v,nt1_v)] * eye;
        }

        for (fint ii = 1; ii <= nterms; ii++) {
            for (fint j = 1; j <= nd_v; j++) {
                ympolex[GI(j,ii-1)] += -beta / 2.0 * ymps[FA3(j,ii+1,jj,nd_v,nt1_v)] * rscale;
                ympolex[GI(j,ii+1)] += -beta / 2.0 * ymps[FA3(j,ii+1,jj,nd_v,nt1_v)] / rscale;
                ympoley[GI(j,ii-1)] +=  beta / 2.0 * ymps[FA3(j,ii+1,jj,nd_v,nt1_v)] * rscale * eye;
                ympoley[GI(j,ii+1)] += -beta / 2.0 * ymps[FA3(j,ii+1,jj,nd_v,nt1_v)] / rscale * eye;

                ympolex[GI(j,ii-1)]   += -beta / 2.0 * mbhmps[FA3(j,ii+1,jj,nd_v,nt1_v)] * rscale;
                mbhmpolex[GI(j,ii+1)] += -beta / 2.0 * mbhmps[FA3(j,ii+1,jj,nd_v,nt1_v)] / rscale;
                ympoley[GI(j,ii-1)]   +=  beta / 2.0 * mbhmps[FA3(j,ii+1,jj,nd_v,nt1_v)] * rscale * eye;
                mbhmpoley[GI(j,ii+1)] += -beta / 2.0 * mbhmps[FA3(j,ii+1,jj,nd_v,nt1_v)] / rscale * eye;
            }
        }

        for (fint i = 1; i <= nt_v; i++) {
            double zdiff[2];
            zdiff[0] = targ[FA2(1,i,2)] - source[FA2(1,jj,2)];
            zdiff[1] = targ[FA2(2,i,2)] - source[FA2(2,jj,2)];
            double r, theta;
            h2cart2polar_(zdiff, &r, &theta);

            if (r < thresh) continue;

            fint ifders = 0;
            double ders_loc[2];
            diffslogbk_fast_(&r, &beta, &rscale, diffs, &ifders,
                             ders_loc, kvec, &nt2);

            mptemp1[0] = diffs[0];
            mptemp2[0] = kvec[0];
            fcomplex ztemp2 = cexp(eye * theta);
            fcomplex ztemp1 = ztemp2;
            for (fint k = 1; k <= nterms + 2; k++) {
                mptemp1[k] = diffs[k] * creal(ztemp1) + diffs[k] * cimag(ztemp1) * I;
                mptemp2[k] = kvec[k] * creal(ztemp1) + kvec[k] * cimag(ztemp1) * I;
                ztemp1 = ztemp1 * ztemp2;
            }

            /* pot */
            for (fint j = 1; j <= nd_v; j++) {
                pot[FA2(j,i,nd_v)] += creal(mptemp1[0]) * creal(mbhmps[FA3(j,0+1,jj,nd_v,nt1_v)]);
                pot[FA2(j,i,nd_v)] += creal(mptemp2[0]) * creal(ymps[FA3(j,0+1,jj,nd_v,nt1_v)]);
            }
            for (fint l = 1; l <= nterms; l++) {
                for (fint j = 1; j <= nd_v; j++) {
                    pot[FA2(j,i,nd_v)] += creal(mptemp1[l]) * creal(mbhmps[FA3(j,l+1,jj,nd_v,nt1_v)]);
                    pot[FA2(j,i,nd_v)] += cimag(mptemp1[l]) * cimag(mbhmps[FA3(j,l+1,jj,nd_v,nt1_v)]);
                    pot[FA2(j,i,nd_v)] += creal(mptemp2[l]) * creal(ymps[FA3(j,l+1,jj,nd_v,nt1_v)]);
                    pot[FA2(j,i,nd_v)] += cimag(mptemp2[l]) * cimag(ymps[FA3(j,l+1,jj,nd_v,nt1_v)]);
                }
            }

            /* grad */
            for (fint j = 1; j <= nd_v; j++) {
                grad[FA3(j,1,i,nd_v,2)] += creal(mptemp1[0]) * creal(mbhmpolex[GI(j,0)]);
                grad[FA3(j,1,i,nd_v,2)] += creal(mptemp2[0]) * creal(ympolex[GI(j,0)]);
                grad[FA3(j,2,i,nd_v,2)] += creal(mptemp1[0]) * creal(mbhmpoley[GI(j,0)]);
                grad[FA3(j,2,i,nd_v,2)] += creal(mptemp2[0]) * creal(ympoley[GI(j,0)]);
            }
            for (fint l = 1; l <= nterms + 1; l++) {
                for (fint j = 1; j <= nd_v; j++) {
                    grad[FA3(j,1,i,nd_v,2)] += creal(mptemp1[l]) * creal(mbhmpolex[GI(j,l)]);
                    grad[FA3(j,1,i,nd_v,2)] += cimag(mptemp1[l]) * cimag(mbhmpolex[GI(j,l)]);
                    grad[FA3(j,1,i,nd_v,2)] += creal(mptemp2[l]) * creal(ympolex[GI(j,l)]);
                    grad[FA3(j,1,i,nd_v,2)] += cimag(mptemp2[l]) * cimag(ympolex[GI(j,l)]);
                    grad[FA3(j,2,i,nd_v,2)] += creal(mptemp1[l]) * creal(mbhmpoley[GI(j,l)]);
                    grad[FA3(j,2,i,nd_v,2)] += cimag(mptemp1[l]) * cimag(mbhmpoley[GI(j,l)]);
                    grad[FA3(j,2,i,nd_v,2)] += creal(mptemp2[l]) * creal(ympoley[GI(j,l)]);
                    grad[FA3(j,2,i,nd_v,2)] += cimag(mptemp2[l]) * cimag(ympoley[GI(j,l)]);
                }
            }
        }
    }
#undef GI
    free(mptemp1); free(mptemp2); free(diffs); free(kvec);
    free(ympolex); free(ympoley); free(mbhmpolex); free(mbhmpoley);
}""")


def emit_mps_h():
    """Emit mbh2d_directmpsh_vec."""
    # The hessian version extends the gradient version with second derivative expansions.
    # I'll read the full Fortran to emit this accurately. For now, a direct translation.
    print("""
void FNAME(mbh2d_directmpsh_vec)(
    const fint *nd_p, const double *beta_p, const double *source, const fint *ns_p,
    const fcomplex *mbhmps, const fcomplex *ymps, const fint *ntermsmps_p,
    const double *targ, const fint *nt_p, double *pot, double *grad, double *hess,
    const double *thresh_p)
{
    fint nd_v = *nd_p, ns_v = *ns_p, nt_v = *nt_p;
    fint ntermsmps = *ntermsmps_p;
    double beta = *beta_p, thresh = *thresh_p;
    double rscale = 1.0;
    fint nterms = ntermsmps;
    fcomplex eye = I;
    fint nt1_v = ntermsmps + 1;

    fint nt2 = nterms + 2;
    fint alloc_sz = nterms + 7;
    fcomplex *mptemp1 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    fcomplex *mptemp2 = (fcomplex *)malloc(alloc_sz * sizeof(fcomplex));
    double *diffs = (double *)malloc(alloc_sz * sizeof(double));
    double *kvec = (double *)malloc(alloc_sz * sizeof(double));

    /* gradient derivative expansions: nd_v x (0:nterms+1) */
    fint gd = nterms + 2;
    fcomplex *ympolex   = (fcomplex *)calloc(nd_v * gd, sizeof(fcomplex));
    fcomplex *ympoley   = (fcomplex *)calloc(nd_v * gd, sizeof(fcomplex));
    fcomplex *mbhmpolex = (fcomplex *)calloc(nd_v * gd, sizeof(fcomplex));
    fcomplex *mbhmpoley = (fcomplex *)calloc(nd_v * gd, sizeof(fcomplex));

    /* hessian derivative expansions: nd_v x (0:nterms+2) */
    fint hd = nterms + 3;
    fcomplex *ympolexx    = (fcomplex *)calloc(nd_v * hd, sizeof(fcomplex));
    fcomplex *ympolexy    = (fcomplex *)calloc(nd_v * hd, sizeof(fcomplex));
    fcomplex *ympoleyy    = (fcomplex *)calloc(nd_v * hd, sizeof(fcomplex));
    fcomplex *mbhmpolexx  = (fcomplex *)calloc(nd_v * hd, sizeof(fcomplex));
    fcomplex *mbhmpolexy  = (fcomplex *)calloc(nd_v * hd, sizeof(fcomplex));
    fcomplex *mbhmpoleyy  = (fcomplex *)calloc(nd_v * hd, sizeof(fcomplex));

#define GI(j, imode)  ((imode) * nd_v + ((j) - 1))
#define HI(j, imode)  ((imode) * nd_v + ((j) - 1))

    for (fint jj = 1; jj <= ns_v; jj++) {

        /* zero gradient expansions */
        for (fint ii = 0; ii < nd_v * gd; ii++) {
            ympolex[ii] = 0; ympoley[ii] = 0;
            mbhmpolex[ii] = 0; mbhmpoley[ii] = 0;
        }

        /* build gradient expansions (same as g version) */
        for (fint j = 1; j <= nd_v; j++) {
            ympolex[GI(j,1)] = -beta / rscale * ymps[FA3(j,0+1,jj,nd_v,nt1_v)];
            ympoley[GI(j,1)] = -beta / rscale * ymps[FA3(j,0+1,jj,nd_v,nt1_v)] * eye;
            mbhmpolex[GI(j,1)] = -beta / rscale * mbhmps[FA3(j,0+1,jj,nd_v,nt1_v)];
            mbhmpoley[GI(j,1)] = -beta / rscale * mbhmps[FA3(j,0+1,jj,nd_v,nt1_v)] * eye;
        }

        for (fint ii = 1; ii <= nterms; ii++) {
            for (fint j = 1; j <= nd_v; j++) {
                ympolex[GI(j,ii-1)] += -beta / 2.0 * ymps[FA3(j,ii+1,jj,nd_v,nt1_v)] * rscale;
                ympolex[GI(j,ii+1)] += -beta / 2.0 * ymps[FA3(j,ii+1,jj,nd_v,nt1_v)] / rscale;
                ympoley[GI(j,ii-1)] +=  beta / 2.0 * ymps[FA3(j,ii+1,jj,nd_v,nt1_v)] * rscale * eye;
                ympoley[GI(j,ii+1)] += -beta / 2.0 * ymps[FA3(j,ii+1,jj,nd_v,nt1_v)] / rscale * eye;

                ympolex[GI(j,ii-1)]   += -beta / 2.0 * mbhmps[FA3(j,ii+1,jj,nd_v,nt1_v)] * rscale;
                mbhmpolex[GI(j,ii+1)] += -beta / 2.0 * mbhmps[FA3(j,ii+1,jj,nd_v,nt1_v)] / rscale;
                ympoley[GI(j,ii-1)]   +=  beta / 2.0 * mbhmps[FA3(j,ii+1,jj,nd_v,nt1_v)] * rscale * eye;
                mbhmpoley[GI(j,ii+1)] += -beta / 2.0 * mbhmps[FA3(j,ii+1,jj,nd_v,nt1_v)] / rscale * eye;
            }
        }

        /* build hessian expansions */
        for (fint ii = 0; ii < nd_v * hd; ii++) {
            ympolexx[ii] = 0; ympolexy[ii] = 0; ympoleyy[ii] = 0;
            mbhmpolexx[ii] = 0; mbhmpolexy[ii] = 0; mbhmpoleyy[ii] = 0;
        }

        for (fint j = 1; j <= nd_v; j++) {
            ympolexx[HI(j,1)]   = -beta / 1.0 / rscale * creal(ympolex[GI(j,0)]);
            ympolexy[HI(j,1)]   = -beta / 1.0 / rscale * creal(ympolex[GI(j,0)]) * eye;
            ympoleyy[HI(j,1)]   = -beta / 1.0 / rscale * creal(ympoley[GI(j,0)]) * eye;
            mbhmpolexx[HI(j,1)] = -beta / 1.0 / rscale * creal(mbhmpolex[GI(j,0)]);
            mbhmpolexy[HI(j,1)] = -beta / 1.0 / rscale * creal(mbhmpolex[GI(j,0)]) * eye;
            mbhmpoleyy[HI(j,1)] = -beta / 1.0 / rscale * creal(mbhmpoley[GI(j,0)]) * eye;
        }

        for (fint ii = 1; ii <= nterms + 1; ii++) {
            for (fint j = 1; j <= nd_v; j++) {
                ympolexx[HI(j,ii-1)] += -beta / 2.0 * ympolex[GI(j,ii)] * rscale;
                ympolexx[HI(j,ii+1)] += -beta / 2.0 * ympolex[GI(j,ii)] / rscale;
                ympolexy[HI(j,ii-1)] +=  beta / 2.0 * ympolex[GI(j,ii)] * rscale * eye;
                ympolexy[HI(j,ii+1)] += -beta / 2.0 * ympolex[GI(j,ii)] / rscale * eye;
                ympoleyy[HI(j,ii-1)] +=  beta / 2.0 * ympoley[GI(j,ii)] * rscale * eye;
                ympoleyy[HI(j,ii+1)] += -beta / 2.0 * ympoley[GI(j,ii)] / rscale * eye;

                ympolexx[HI(j,ii-1)]   += -beta / 2.0 * mbhmpolex[GI(j,ii)] * rscale;
                mbhmpolexx[HI(j,ii+1)] += -beta / 2.0 * mbhmpolex[GI(j,ii)] / rscale;
                ympolexy[HI(j,ii-1)]   +=  beta / 2.0 * mbhmpolex[GI(j,ii)] * rscale * eye;
                mbhmpolexy[HI(j,ii+1)] += -beta / 2.0 * mbhmpolex[GI(j,ii)] / rscale * eye;
                ympoleyy[HI(j,ii-1)]   +=  beta / 2.0 * mbhmpoley[GI(j,ii)] * rscale * eye;
                mbhmpoleyy[HI(j,ii+1)] += -beta / 2.0 * mbhmpoley[GI(j,ii)] / rscale * eye;
            }
        }

        for (fint i = 1; i <= nt_v; i++) {
            double zdiff[2];
            zdiff[0] = targ[FA2(1,i,2)] - source[FA2(1,jj,2)];
            zdiff[1] = targ[FA2(2,i,2)] - source[FA2(2,jj,2)];
            double r, theta;
            h2cart2polar_(zdiff, &r, &theta);

            if (r < thresh) continue;

            fint ifders = 0;
            double ders_loc[2];
            diffslogbk_fast_(&r, &beta, &rscale, diffs, &ifders,
                             ders_loc, kvec, &nt2);

            mptemp1[0] = diffs[0];
            mptemp2[0] = kvec[0];
            fcomplex ztemp2 = cexp(eye * theta);
            fcomplex ztemp1 = ztemp2;
            for (fint k = 1; k <= nterms + 2; k++) {
                mptemp1[k] = diffs[k] * creal(ztemp1) + diffs[k] * cimag(ztemp1) * I;
                mptemp2[k] = kvec[k] * creal(ztemp1) + kvec[k] * cimag(ztemp1) * I;
                ztemp1 = ztemp1 * ztemp2;
            }

            /* pot */
            for (fint j = 1; j <= nd_v; j++) {
                pot[FA2(j,i,nd_v)] += creal(mptemp1[0]) * creal(mbhmps[FA3(j,0+1,jj,nd_v,nt1_v)]);
                pot[FA2(j,i,nd_v)] += creal(mptemp2[0]) * creal(ymps[FA3(j,0+1,jj,nd_v,nt1_v)]);
            }
            for (fint l = 1; l <= nterms; l++) {
                for (fint j = 1; j <= nd_v; j++) {
                    pot[FA2(j,i,nd_v)] += creal(mptemp1[l]) * creal(mbhmps[FA3(j,l+1,jj,nd_v,nt1_v)]);
                    pot[FA2(j,i,nd_v)] += cimag(mptemp1[l]) * cimag(mbhmps[FA3(j,l+1,jj,nd_v,nt1_v)]);
                    pot[FA2(j,i,nd_v)] += creal(mptemp2[l]) * creal(ymps[FA3(j,l+1,jj,nd_v,nt1_v)]);
                    pot[FA2(j,i,nd_v)] += cimag(mptemp2[l]) * cimag(ymps[FA3(j,l+1,jj,nd_v,nt1_v)]);
                }
            }

            /* grad */
            for (fint j = 1; j <= nd_v; j++) {
                grad[FA3(j,1,i,nd_v,2)] += creal(mptemp1[0]) * creal(mbhmpolex[GI(j,0)]);
                grad[FA3(j,1,i,nd_v,2)] += creal(mptemp2[0]) * creal(ympolex[GI(j,0)]);
                grad[FA3(j,2,i,nd_v,2)] += creal(mptemp1[0]) * creal(mbhmpoley[GI(j,0)]);
                grad[FA3(j,2,i,nd_v,2)] += creal(mptemp2[0]) * creal(ympoley[GI(j,0)]);
            }
            for (fint l = 1; l <= nterms + 1; l++) {
                for (fint j = 1; j <= nd_v; j++) {
                    grad[FA3(j,1,i,nd_v,2)] += creal(mptemp1[l]) * creal(mbhmpolex[GI(j,l)]);
                    grad[FA3(j,1,i,nd_v,2)] += cimag(mptemp1[l]) * cimag(mbhmpolex[GI(j,l)]);
                    grad[FA3(j,1,i,nd_v,2)] += creal(mptemp2[l]) * creal(ympolex[GI(j,l)]);
                    grad[FA3(j,1,i,nd_v,2)] += cimag(mptemp2[l]) * cimag(ympolex[GI(j,l)]);
                    grad[FA3(j,2,i,nd_v,2)] += creal(mptemp1[l]) * creal(mbhmpoley[GI(j,l)]);
                    grad[FA3(j,2,i,nd_v,2)] += cimag(mptemp1[l]) * cimag(mbhmpoley[GI(j,l)]);
                    grad[FA3(j,2,i,nd_v,2)] += creal(mptemp2[l]) * creal(ympoley[GI(j,l)]);
                    grad[FA3(j,2,i,nd_v,2)] += cimag(mptemp2[l]) * cimag(ympoley[GI(j,l)]);
                }
            }

            /* hess */
            for (fint j = 1; j <= nd_v; j++) {
                hess[FA3(j,1,i,nd_v,3)] += creal(mptemp1[0]) * creal(mbhmpolexx[HI(j,0)]);
                hess[FA3(j,1,i,nd_v,3)] += creal(mptemp2[0]) * creal(ympolexx[HI(j,0)]);
                hess[FA3(j,2,i,nd_v,3)] += creal(mptemp1[0]) * creal(mbhmpolexy[HI(j,0)]);
                hess[FA3(j,2,i,nd_v,3)] += creal(mptemp2[0]) * creal(ympolexy[HI(j,0)]);
                hess[FA3(j,3,i,nd_v,3)] += creal(mptemp1[0]) * creal(mbhmpoleyy[HI(j,0)]);
                hess[FA3(j,3,i,nd_v,3)] += creal(mptemp2[0]) * creal(ympoleyy[HI(j,0)]);
            }
            for (fint l = 1; l <= nterms + 2; l++) {
                for (fint j = 1; j <= nd_v; j++) {
                    hess[FA3(j,1,i,nd_v,3)] += creal(mptemp1[l]) * creal(mbhmpolexx[HI(j,l)]);
                    hess[FA3(j,1,i,nd_v,3)] += cimag(mptemp1[l]) * cimag(mbhmpolexx[HI(j,l)]);
                    hess[FA3(j,1,i,nd_v,3)] += creal(mptemp2[l]) * creal(ympolexx[HI(j,l)]);
                    hess[FA3(j,1,i,nd_v,3)] += cimag(mptemp2[l]) * cimag(ympolexx[HI(j,l)]);
                    hess[FA3(j,2,i,nd_v,3)] += creal(mptemp1[l]) * creal(mbhmpolexy[HI(j,l)]);
                    hess[FA3(j,2,i,nd_v,3)] += cimag(mptemp1[l]) * cimag(mbhmpolexy[HI(j,l)]);
                    hess[FA3(j,2,i,nd_v,3)] += creal(mptemp2[l]) * creal(ympolexy[HI(j,l)]);
                    hess[FA3(j,2,i,nd_v,3)] += cimag(mptemp2[l]) * cimag(ympolexy[HI(j,l)]);
                    hess[FA3(j,3,i,nd_v,3)] += creal(mptemp1[l]) * creal(mbhmpoleyy[HI(j,l)]);
                    hess[FA3(j,3,i,nd_v,3)] += cimag(mptemp1[l]) * cimag(mbhmpoleyy[HI(j,l)]);
                    hess[FA3(j,3,i,nd_v,3)] += creal(mptemp2[l]) * creal(ympoleyy[HI(j,l)]);
                    hess[FA3(j,3,i,nd_v,3)] += cimag(mptemp2[l]) * cimag(ympoleyy[HI(j,l)]);
                }
            }
        }
    }
#undef GI
#undef HI
    free(mptemp1); free(mptemp2); free(diffs); free(kvec);
    free(ympolex); free(ympoley); free(mbhmpolex); free(mbhmpoley);
    free(ympolexx); free(ympolexy); free(ympoleyy);
    free(mbhmpolexx); free(mbhmpolexy); free(mbhmpoleyy);
}""")


def main():
    emit_header()
    for rout in direct_routs:
        emit_direct_routine(rout)
    emit_mps_p()
    emit_mps_g()
    emit_mps_h()

if __name__ == "__main__":
    main()
